const DADOS_CALENDARIO = {
  "titulo": "Calendário Editorial Oficial Trudata ERP — 2026",
  "periodo": "15 de Setembro a 31 de Dezembro de 2026",
  "total_dias": 108,
  "total_feed": 17,
  "stories_diarios": [
    {
      "data": "15/09",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Dia do Cliente",
      "visual": "Vídeo da equipe",
      "tela1": "Hoje é dia de agradecer a quem confia na Trudata.",
      "tela2": "Cada conversa com nossos clientes ajuda a entender melhor a rotina das empresas.",
      "tela3": "Qual parte da sua rotina você gostaria de simplificar? Responda aqui.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "15/09",
        "dia_semana": "terça-feira",
        "tipo": "Reels",
        "ideia": "Obrigado por compartilhar sua rotina com a Trudata",
        "producao": "Reel de 25 a 35 segundos · 0–4s: equipe agradece. 4–20s: três colaboradores contam o tipo de necessidade que escutam, sem citar clientes. 20–30s: convite para o público compartilhar uma dificuldade.",
        "legenda": "Hoje nosso agradecimento vai para quem confia na Trudata e divide com a gente os desafios da sua empresa. Qual rotina você gostaria de simplificar?",
        "chamada": "Responder nos comentários.",
        "material": "Vídeos da equipe; legendas; nenhum depoimento ou resultado inventado."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "⭐ Dia do Cliente",
        "desc": "Comemoração nacional de valorização dos clientes"
      }
    },
    {
      "data": "16/09",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Conheça a Trudata",
      "visual": "Apresentador e imagens de trabalho",
      "tela1": "Sua empresa vende, compra, atende e paga contas. Como tudo isso se conecta?",
      "tela2": "A Trudata trabalha com sistemas de gestão para diferentes rotinas de negócio.",
      "tela3": "Qual é seu segmento? Comércio / Serviços / Farmácia / Moda.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "17/09",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Estoque na prática",
      "visual": "Cartões com produto fictício",
      "tela1": "A venda estava quase fechada. Mas o produto não estava na prateleira.",
      "tela2": "Comparar o saldo registrado com o estoque físico ajuda a identificar divergências.",
      "tela3": "Isso acontece na sua loja? Sim / Às vezes.",
      "opcoes_enquete": [
        "Sim",
        "Às vezes"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "18/09",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Semana Farroupilha",
      "visual": "Foto local autorizada",
      "tela1": "O comércio também faz parte das histórias do nosso Rio Grande.",
      "tela2": "Nesta Semana Farroupilha, valorize quem atende, produz e empreende perto de você.",
      "tela3": "Qual negócio da sua cidade merece ser conhecido? Conte para nós.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "19/09",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Dia do Comprador",
      "visual": "Lista animada",
      "tela1": "Comprar bem começa antes de falar com o fornecedor.",
      "tela2": "Revise o que vendeu, o que sobrou e quando cada item precisa ser reposto.",
      "tela3": "Na próxima compra, você vai olhar primeiro: Giro / Saldo?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "🛒 Dia do Comprador",
        "desc": "Data profissional"
      }
    },
    {
      "data": "20/09",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Dia do Gaúcho",
      "visual": "Equipe e referência visual ao RS",
      "tela1": "20 de setembro. Um dia para celebrar nossas raízes gaúchas.",
      "tela2": "De Sarandi, nosso abraço a quem faz parte da vida e do comércio do Rio Grande do Sul.",
      "tela3": "De qual cidade você acompanha a Trudata?",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "20/09",
        "dia_semana": "domingo",
        "tipo": "Reels",
        "ideia": "De Sarandi para as histórias do comércio gaúcho",
        "producao": "Reel de 20 a 30 segundos · Abrir com referência a Sarandi; mostrar equipe e registros locais autorizados; terminar com mensagem de valorização da cultura e das pessoas do RS.",
        "legenda": "Neste 20 de setembro, celebramos nossas raízes e as pessoas que fazem o Rio Grande do Sul acontecer. Um abraço da equipe Trudata a todas as cidades que caminham conosco.",
        "chamada": "Comentar a cidade de onde acompanha a empresa.",
        "material": "Imagens próprias; referências regionais sem caricatura; evitar sugerir parceria com eventos."
      },
      "ocasiao": {
        "tipo": "feriado_rs",
        "badge": "🟢 Feriado Farroupilha",
        "desc": "Feriado Estadual no RS (Dia do Gaúcho)"
      }
    },
    {
      "data": "21/09",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Dia da Árvore e inclusão",
      "visual": "Arte com tipografia acessível",
      "tela1": "Pequenas melhorias também fazem parte da rotina de uma empresa.",
      "tela2": "Reduzir impressões desnecessárias e tornar as informações mais legíveis são bons começos.",
      "tela3": "Qual melhoria simples sua equipe pode colocar em prática nesta semana?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "conscientizacao",
        "badge": "🌳 Dia da Árvore & PCD",
        "desc": "Conscientização ambiental e inclusão"
      }
    },
    {
      "data": "22/09",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Dia do Contador",
      "visual": "Vídeo de agradecimento",
      "tela1": "Hoje, nosso reconhecimento a quem transforma registros em orientação.",
      "tela2": "Organizar os documentos e combinar uma rotina de envio facilita a relação com a contabilidade.",
      "tela3": "Que tal agradecer hoje ao contador que acompanha sua empresa?",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "22/09",
        "dia_semana": "terça-feira",
        "tipo": "Carrossel",
        "ideia": "Uma boa parceria com a contabilidade começa na rotina",
        "producao": "Carrossel de 5 telas · 1: homenagem. 2: organizar documentos. 3: combinar periodicidade de envio. 4: conferir pendências com o contador. 5: agradecimento e convite para compartilhar.",
        "legenda": "No Dia do Contador, reconhecemos quem acompanha decisões importantes das empresas. Organização e comunicação ajudam essa parceria a funcionar melhor todos os dias.",
        "chamada": "Compartilhar com o contador.",
        "material": "Arte simples; não ensinar regra fiscal nem anunciar prazo de obrigação."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "💼 Dia do Contador",
        "desc": "Homenagem aos parceiros contábeis"
      }
    },
    {
      "data": "23/09",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Nova estação",
      "visual": "Foto de produtos por coleção",
      "tela1": "A primavera começou ontem à noite. Sua coleção está organizada?",
      "tela2": "Na moda, separar produtos por tamanho, cor e temporada ajuda a enxergar o estoque.",
      "tela3": "Qual detalhe mais dá trabalho? Tamanho / Cor.",
      "opcoes_enquete": [
        "Tamanho",
        "Cor"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "sazonal",
        "badge": "🌸 Início da Primavera",
        "desc": "Mudança de estação"
      }
    },
    {
      "data": "24/09",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Caixa organizado",
      "visual": "Cartões de entradas e saídas",
      "tela1": "Vender hoje significa receber hoje?",
      "tela2": "Separe as vendas realizadas dos valores que realmente entraram no caixa.",
      "tela3": "Você acompanha seus recebimentos? Diariamente / Quero melhorar.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "25/09",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Dia Mundial do Farmacêutico",
      "visual": "Foto autorizada ou arte",
      "tela1": "Nosso reconhecimento aos farmacêuticos e à sua responsabilidade diária.",
      "tela2": "Nesta data promovida pela FIP, valorizamos quem orienta e cuida das pessoas.",
      "tela3": "Deixe uma mensagem de agradecimento a um farmacêutico.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "25/09",
        "dia_semana": "sexta-feira",
        "tipo": "Reels",
        "ideia": "Nosso reconhecimento a quem cuida com responsabilidade",
        "producao": "Reel de 20 a 30 segundos · Abrir com homenagem; mostrar profissional autorizado ou equipe fazendo o agradecimento; concluir sem demonstração de medicamento ou promessa clínica.",
        "legenda": "No Dia Mundial do Farmacêutico, promovido pela FIP, nosso reconhecimento a quem dedica conhecimento e responsabilidade ao cuidado com as pessoas.",
        "chamada": "Deixar uma mensagem de reconhecimento.",
        "material": "Autorização do participante; arte própria; não utilizar a identidade oficial da campanha como anúncio comercial."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "💊 Dia do Farmacêutico",
        "desc": "Data profissional internacional (FIP)"
      }
    },
    {
      "data": "26/09",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Dia Nacional dos Surdos",
      "visual": "Vídeo legendado",
      "tela1": "Seu cliente consegue entender seu conteúdo sem ouvir o áudio?",
      "tela2": "Legendas revisadas, bom contraste e instruções escritas tornam a comunicação mais acessível.",
      "tela3": "Hoje, revise um vídeo da sua empresa com o som desligado.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "conscientizacao",
        "badge": "🤟 Dia dos Surdos",
        "desc": "Acessibilidade na comunicação"
      }
    },
    {
      "data": "27/09",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Dia Mundial do Turismo",
      "visual": "Foto do comércio local",
      "tela1": "Quem visita uma cidade também conhece seu comércio.",
      "tela2": "Informações claras sobre localização, produtos e atendimento ajudam quem chega pela primeira vez.",
      "tela3": "O que você indicaria para alguém conhecer na sua cidade?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "setorial",
        "badge": "✈️ Dia do Turismo",
        "desc": "Comércio receptivo"
      }
    },
    {
      "data": "28/09",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Informação acessível",
      "visual": "Apresentador",
      "tela1": "Uma informação existe. Mas a equipe sabe onde encontrá-la?",
      "tela2": "Organize os procedimentos mais usados em um lugar conhecido por todos.",
      "tela3": "Qual orientação a sua equipe mais precisa repetir?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "29/09",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Menos desperdício",
      "visual": "Ilustração de prateleira",
      "tela1": "O que está parado no estoque há tempo demais?",
      "tela2": "Revisar validade, giro e reposição ajuda a planejar o uso dos recursos da empresa.",
      "tela3": "Escolha hoje uma categoria para revisar.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "30/09",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Dia da Secretária e fechamento",
      "visual": "Bastidor administrativo",
      "tela1": "Nosso reconhecimento a quem organiza agendas, documentos e atendimentos.",
      "tela2": "Para fechar setembro, confira pendências e defina quem acompanha cada uma.",
      "tela3": "Qual pendência você quer resolver antes de outubro?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "📋 Dia da Secretária",
        "desc": "Reconhecimento aos organizadores"
      }
    },
    {
      "data": "01/10",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Dia do Vendedor",
      "visual": "Vídeo de equipe",
      "tela1": "Quem vende também escuta, orienta e encontra soluções.",
      "tela2": "Neste Dia do Vendedor, agradecemos a quem está na linha de frente do atendimento.",
      "tela3": "Qual qualidade você mais valoriza em um vendedor?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "🤝 Dia do Vendedor",
        "desc": "Reconhecimento da linha de frente comercial"
      }
    },
    {
      "data": "02/10",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Outubro Rosa",
      "visual": "Arte institucional",
      "tela1": "Outubro Rosa é um convite à informação e ao cuidado.",
      "tela2": "Busque orientações sobre saúde da mulher em fontes confiáveis e com profissionais de saúde.",
      "tela3": "Acesse o conteúdo do INCA pelo link deste story.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "campanha",
        "badge": "🎀 Outubro Rosa",
        "desc": "Início da campanha oficial de conscientização"
      }
    },
    {
      "data": "03/10",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Pequeno negócio organizado",
      "visual": "Apresentador",
      "tela1": "Seu negócio cresceu. A rotina acompanhou?",
      "tela2": "Anote as tarefas que ainda dependem de papéis soltos ou de uma única pessoa.",
      "tela3": "Qual tarefa você gostaria de organizar primeiro?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "04/10",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Comércio do bairro",
      "visual": "Foto de fachada autorizada",
      "tela1": "Hoje, que tal olhar com atenção para os negócios da sua região?",
      "tela2": "Uma indicação pode apresentar um bom serviço a quem ainda não o conhece.",
      "tela3": "Conte uma experiência boa com o comércio local.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "05/10",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Dia da Micro e Pequena Empresa",
      "visual": "Vídeo de agradecimento",
      "tela1": "Por trás de um pequeno negócio existe uma grande rotina.",
      "tela2": "A Trudata apresenta o Easy para quem busca uma solução web para emissão e gestão fiscal.",
      "tela3": "Quer entender se ele atende sua operação? Responda EASY.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "05/10",
        "dia_semana": "segunda-feira",
        "tipo": "Reels",
        "ideia": "Qual rotina do seu pequeno negócio precisa se organizar primeiro",
        "producao": "Reel de 30 segundos · Mostrar três situações encenadas: documentos espalhados, busca de informação e dúvida sobre emissão. Apresentar o Easy como solução web divulgada pela Trudata; convidar para avaliar aderência.",
        "legenda": "No Dia da Micro e Pequena Empresa, valorizamos quem empreende todos os dias. Se organizar a emissão fiscal é uma prioridade, conheça a proposta do Trudata Easy e converse com nossa equipe.",
        "chamada": "Solicitar uma demonstração pelo link da bio.",
        "material": "Captura de demonstração validada do Easy; confirmar condições de contratação antes de incluí-las."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "🏢 Dia da Micro e Peq. Empresa",
        "desc": "Público central do Trudata Easy e ERP"
      }
    },
    {
      "data": "06/10",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Preparação para Dia das Crianças",
      "visual": "Lista na tela",
      "tela1": "Falta menos de uma semana para o Dia das Crianças.",
      "tela2": "Confira produtos, preços e informações que sua equipe precisa para atender.",
      "tela3": "O que ainda falta revisar? Estoque / Atendimento.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "07/10",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Cadastro de produtos",
      "visual": "Tela demonstrativa validada",
      "tela1": "Dois nomes diferentes para o mesmo produto podem confundir a equipe.",
      "tela2": "Defina um padrão de descrição e revise os cadastros duplicados.",
      "tela3": "Escolha cinco cadastros para conferir hoje.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "08/10",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Atendimento entre gerações",
      "visual": "Apresentador",
      "tela1": "Cada cliente tem um jeito de comprar e de pedir ajuda.",
      "tela2": "Explique com clareza, ofereça tempo e evite pressupor familiaridade com tecnologia.",
      "tela3": "Seu atendimento oferece instruções por escrito? Sim / Vamos preparar.",
      "opcoes_enquete": [
        "Sim",
        "Vamos preparar"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "09/10",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Conferência antes do movimento",
      "visual": "Checklist animado",
      "tela1": "O fim de semana está chegando. Sua operação está preparada?",
      "tela2": "Revise os itens de maior procura e alinhe com a equipe as condições anunciadas.",
      "tela3": "Salve um lembrete: conferir antes de abrir.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "10/10",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Dia Mundial da Saúde Mental",
      "visual": "Arte tranquila",
      "tela1": "Cuidar das pessoas também faz parte da rotina de trabalho.",
      "tela2": "Ouvir com respeito e buscar apoio profissional quando necessário são atitudes importantes.",
      "tela3": "Reserve um momento para perguntar à sua equipe como ela está.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "conscientizacao",
        "badge": "🧠 Saúde Mental",
        "desc": "Dia Mundial da Saúde Mental"
      }
    },
    {
      "data": "11/10",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Feriado à vista",
      "visual": "Calendário simples",
      "tela1": "Amanhã é feriado nacional de Nossa Senhora Aparecida e Dia das Crianças.",
      "tela2": "Deixe claros os horários de atendimento que sua empresa realmente adotará.",
      "tela3": "Seu aviso de funcionamento já está atualizado?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "12/10",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Dia das Crianças",
      "visual": "Ilustração sem fotos de menores",
      "tela1": "Um dia para valorizar a infância, a curiosidade e o direito de brincar.",
      "tela2": "Que as crianças tenham espaço para aprender, imaginar e se desenvolver.",
      "tela3": "Qual brincadeira marcou sua infância?",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "12/10",
        "dia_semana": "segunda-feira",
        "tipo": "Post Estático",
        "ideia": "Um dia para valorizar a infância",
        "producao": "Post estático · Ilustração original de brincadeiras; frase principal curta; legenda acolhedora. Evitar usar criança como porta-voz comercial.",
        "legenda": "Que toda criança tenha espaço para brincar, aprender e imaginar. A equipe Trudata deseja um Dia das Crianças com cuidado e bons momentos.",
        "chamada": "Compartilhar uma lembrança de infância, se desejar.",
        "material": "Preferir ilustração; se houver fotos de menores, obter autorização dos responsáveis."
      },
      "ocasiao": {
        "tipo": "feriado_nacional",
        "badge": "🔴 Feriado Nacional: N. Sra. Aparecida / Crianças",
        "desc": "Feriado Nacional"
      }
    },
    {
      "data": "13/10",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Depois da campanha",
      "visual": "Gráfico ilustrativo",
      "tela1": "Como foi o movimento do Dia das Crianças?",
      "tela2": "Compare produtos vendidos, sobras e dúvidas frequentes para aprender com a campanha.",
      "tela3": "Qual foi seu principal aprendizado? Conte em uma frase.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "14/10",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Serviços organizados",
      "visual": "Ordem de serviço fictícia",
      "tela1": "Seu cliente perguntou pelo serviço. Você sabe em que etapa ele está?",
      "tela2": "Uma ordem de serviço bem preenchida reúne a solicitação e o acompanhamento do trabalho.",
      "tela3": "Hoje você registra: Em sistema / Em anotações.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "15/10",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Dia do Professor",
      "visual": "Vídeo de colaborador",
      "tela1": "Hoje agradecemos a quem ensina e compartilha conhecimento.",
      "tela2": "Na empresa, um treinamento claro também ajuda a equipe a trabalhar com mais confiança.",
      "tela3": "Quem ensinou algo importante para você? Deixe seu agradecimento.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "📚 Dia do Professor",
        "desc": "Educação e treinamento"
      }
    },
    {
      "data": "16/10",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Alimentação e pão",
      "visual": "Foto de padaria autorizada",
      "tela1": "Nosso reconhecimento a quem produz e comercializa alimentos todos os dias.",
      "tela2": "Conhecer a procura e acompanhar os produtos ajuda a planejar a reposição.",
      "tela3": "Na sua operação, o que pesa mais? Falta / Sobra.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "🥖 Alimentação & Pão",
        "desc": "Padarias e mercados"
      }
    },
    {
      "data": "17/10",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Bastidor de treinamento",
      "visual": "Colaborador apresenta passo a passo validado",
      "tela1": "Uma dúvida comum merece uma explicação que todos entendam.",
      "tela2": "Um passo a passo claro ajuda a equipe a consultar a orientação sempre que precisar.",
      "tela3": "Qual assunto você quer ver em um tutorial?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "18/10",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Planejar a semana",
      "visual": "Lista editável na arte",
      "tela1": "Antes de começar outra semana, escolha uma prioridade.",
      "tela2": "Pode ser revisar compras, acompanhar recebimentos ou organizar atendimentos.",
      "tela3": "Qual será a sua? Compras / Caixa / Atendimento.",
      "opcoes_enquete": [
        "Compras",
        "Caixa",
        "Atendimento"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "19/10",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Inovação e profissionais de TI",
      "visual": "Bastidor de desenvolvimento",
      "tela1": "Inovar começa entendendo uma dificuldade real.",
      "tela2": "Hoje valorizamos os profissionais que transformam necessidades em soluções de tecnologia.",
      "tela3": "Que tarefa repetitiva você gostaria de simplificar?",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "19/10",
        "dia_semana": "segunda-feira",
        "tipo": "Reels",
        "ideia": "Toda melhoria começa com uma pergunta",
        "producao": "Reel de 30 a 40 segundos · 0–5s: qual tarefa dá trabalho. 5–15s: equipe entende a necessidade. 15–30s: bastidor de teste de rotina já existente. Final: valorização dos profissionais de tecnologia.",
        "legenda": "No Dia Nacional da Inovação, mostramos o valor de entender a rotina antes de propor uma solução. Nosso reconhecimento aos profissionais de TI que participam desse trabalho.",
        "chamada": "Comentar uma tarefa que gostaria de simplificar.",
        "material": "Bastidores reais; não apresentar rotina existente como lançamento nem prometer recurso futuro."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "💡 Dia da Inovação & TI",
        "desc": "Tecnologia da Informação"
      }
    },
    {
      "data": "20/10",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Dados para decidir",
      "visual": "Gráfico claramente ilustrativo",
      "tela1": "Qual informação você consulta antes de comprar mais produtos?",
      "tela2": "Compare o histórico de vendas com o saldo atual e a previsão de procura.",
      "tela3": "Você decide com: Histórico / Percepção / Os dois.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "21/10",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Filiais",
      "visual": "Mapa ilustrativo de duas lojas",
      "tela1": "Um produto pode faltar em uma loja e sobrar em outra.",
      "tela2": "Acompanhar as informações das unidades ajuda a planejar a distribuição do estoque.",
      "tela3": "Sua empresa tem mais de uma unidade? Sim / Ainda não.",
      "opcoes_enquete": [
        "Sim",
        "Ainda não"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "22/10",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Começar a Black Friday",
      "visual": "Calendário e apresentador",
      "tela1": "A Black Friday será em 27 de novembro. O planejamento começa agora.",
      "tela2": "Escolha as categorias que fazem sentido para sua operação e revise os custos.",
      "tela3": "Sua empresa vai participar? Sim / Estamos avaliando.",
      "opcoes_enquete": [
        "Sim",
        "Estamos avaliando"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "23/10",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Preço com critério",
      "visual": "Etiquetas fictícias",
      "tela1": "Um desconto precisa caber na realidade do negócio.",
      "tela2": "Antes de divulgar, avalie custo, despesas e margem desejada com o responsável financeiro.",
      "tela3": "Qual será sua primeira revisão? Custo / Preço.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "24/10",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Uma dúvida por vez",
      "visual": "Apresentador",
      "tela1": "ERP e emissão fiscal são a mesma necessidade?",
      "tela2": "Algumas empresas precisam integrar várias rotinas; outras começam pela emissão de documentos.",
      "tela3": "Conte seu cenário para a Trudata indicar uma demonstração adequada.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "25/10",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Dia do Sapateiro",
      "visual": "Foto de calçados",
      "tela1": "Hoje valorizamos o trabalho de quem conhece cada detalhe de um calçado.",
      "tela2": "Para quem vende, acompanhar a grade ajuda a entender quais numerações têm mais procura.",
      "tela3": "Qual numeração mais falta na sua loja?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "👞 Dia do Sapateiro",
        "desc": "Setor calçadista"
      }
    },
    {
      "data": "26/10",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Organizar a reposição",
      "visual": "Lista de compras fictícia",
      "tela1": "Antes de pedir tudo de novo, veja o que realmente precisa voltar.",
      "tela2": "Priorize os itens de maior giro e confirme os prazos com os fornecedores.",
      "tela3": "Você já revisou a próxima compra da semana?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "27/10",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Conversa com o suporte",
      "visual": "Vídeo da equipe",
      "tela1": "Explicar bem uma dúvida ajuda a iniciar o atendimento.",
      "tela2": "Informe a tarefa, a mensagem exibida e o momento em que a dificuldade ocorreu.",
      "tela3": "Salve esta orientação para seu próximo contato.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "28/10",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Organização de documentos",
      "visual": "Tela genérica sem dados reais",
      "tela1": "Encontrar um documento não deveria depender da memória de alguém.",
      "tela2": "Defina um padrão de organização e combine quem acompanha os envios.",
      "tela3": "Qual documento sua equipe mais procura?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "29/10",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Dia Nacional do Livro",
      "visual": "Colaborador com livro",
      "tela1": "Uma boa leitura pode trazer uma ideia para a rotina.",
      "tela2": "Compartilhe um livro que ajudou você a entender pessoas, negócios ou tecnologia.",
      "tela3": "Qual leitura você indica? Responda aqui.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "30/10",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Dia do Comerciário",
      "visual": "Montagem da equipe",
      "tela1": "Hoje é dia de reconhecer quem faz o comércio acontecer.",
      "tela2": "Atendimento, organização e cuidado com o cliente passam pelo trabalho dessas pessoas.",
      "tela3": "Deixe seu agradecimento a quem trabalha com você.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "30/10",
        "dia_semana": "sexta-feira",
        "tipo": "Reels",
        "ideia": "Quem faz o comércio acontecer",
        "producao": "Reel de 20 a 30 segundos · Sequência de funções: atendimento, organização, reposição e caixa. Cada pessoa aparece por alguns segundos; finalizar com agradecimento coletivo.",
        "legenda": "Hoje nosso reconhecimento vai a quem trabalha no comércio e cuida de tantos detalhes para atender bem. Feliz Dia do Comerciário.",
        "chamada": "Marcar um colega, se desejar.",
        "material": "Equipe ou clientes com autorização; não prometer alteração do funcionamento na data."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "🏪 Dia do Comerciário",
        "desc": "Homenagem aos trabalhadores do comércio"
      }
    },
    {
      "data": "31/10",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Halloween e mês encerrado",
      "visual": "Animação leve",
      "tela1": "Um susto de gestão: descobrir a falta do produto depois de anunciar.",
      "tela2": "Feche outubro revisando estoque e preparando os itens da próxima campanha.",
      "tela3": "Qual susto você quer evitar em novembro?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "sazonal",
        "badge": "🎃 Halloween / Fim do Mês",
        "desc": "Fechamento de outubro"
      }
    },
    {
      "data": "01/11",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Novembro Azul",
      "visual": "Arte institucional",
      "tela1": "Novembro Azul: a saúde do homem merece atenção durante todo o ano.",
      "tela2": "Informação confiável e acompanhamento profissional ajudam a cuidar da saúde de forma integral.",
      "tela3": "Confira as orientações do Ministério da Saúde no link.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "campanha",
        "badge": "💙 Novembro Azul",
        "desc": "Campanha de conscientização saúde masculina"
      }
    },
    {
      "data": "02/11",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Finados",
      "visual": "Arte sóbria",
      "tela1": "Hoje é um dia de memória e respeito.",
      "tela2": "Nossa solidariedade a quem sente a ausência de alguém querido.",
      "tela3": "A equipe Trudata deseja um dia de acolhimento e serenidade.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "feriado_nacional",
        "badge": "🔴 Feriado Nacional: Finados",
        "desc": "Feriado Nacional (tom solene e respeitoso)"
      }
    },
    {
      "data": "03/11",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Plano de novembro",
      "visual": "Calendário na tela",
      "tela1": "Novembro começou. Quais são as prioridades da sua empresa?",
      "tela2": "Distribua as revisões de estoque, atendimento e recebimentos ao longo do mês.",
      "tela3": "Qual frente exige mais atenção agora?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "04/11",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Produtos da campanha",
      "visual": "Lista de itens fictícios",
      "tela1": "Nem todo produto precisa entrar na Black Friday.",
      "tela2": "Escolha os itens considerando procura, disponibilidade e condições de venda.",
      "tela3": "Sua seleção já está pronta? Sim / Em revisão.",
      "opcoes_enquete": [
        "Sim",
        "Em revisão"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "05/11",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Descrição que ajuda",
      "visual": "Comparação de cadastros",
      "tela1": "Uma descrição clara facilita encontrar o produto certo.",
      "tela2": "Revise marca, modelo e variações importantes para sua operação.",
      "tela3": "Qual cadastro você pode melhorar hoje?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "06/11",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Compromissos do mês",
      "visual": "Agenda financeira ilustrativa",
      "tela1": "Seu caixa precisa acompanhar o calendário de compromissos.",
      "tela2": "Liste pagamentos e recebimentos previstos para evitar decisões sem contexto.",
      "tela3": "Você faz essa revisão: Semanal / Mensal.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "07/11",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Dúvida de lojista",
      "visual": "Vídeo curto",
      "tela1": "O que você gostaria de aprender sobre organização da loja?",
      "tela2": "Reúna as dúvidas da equipe e escolha uma para resolver por vez.",
      "tela3": "Envie sua pergunta sobre estoque, vendas ou caixa.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "08/11",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Preparar o atendimento",
      "visual": "Enquete em arte",
      "tela1": "Sua equipe conhece as condições das próximas campanhas?",
      "tela2": "Uma conversa breve sobre produtos e regras evita informações desencontradas.",
      "tela3": "O alinhamento já foi feito? Sim / Será nesta semana.",
      "opcoes_enquete": [
        "Sim",
        "Será nesta semana"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "09/11",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Loja física e virtual",
      "visual": "Esquema ilustrativo",
      "tela1": "O cliente vê o mesmo produto em diferentes canais.",
      "tela2": "A integração entre canais depende das soluções contratadas e da configuração da operação.",
      "tela3": "Quer avaliar esse cenário com a Trudata? Responda CANAIS.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "10/11",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Conferência de saldos",
      "visual": "Tela demonstrativa",
      "tela1": "O saldo no cadastro corresponde ao que está disponível?",
      "tela2": "Confira uma amostra dos produtos da campanha antes de liberar a divulgação.",
      "tela3": "Hoje, revise os dez itens de maior procura.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "11/11",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Data dupla do varejo",
      "visual": "Arte com 11 11",
      "tela1": "O 11.11 é uma oportunidade comercial para algumas operações.",
      "tela2": "Se participar, confirme preço, disponibilidade e condições antes de divulgar.",
      "tela3": "Sua empresa usa datas duplas? Sim / Ainda não.",
      "opcoes_enquete": [
        "Sim",
        "Ainda não"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comercial",
        "badge": "🏷️ 11.11 Data Dupla",
        "desc": "Aquece para compras de fim de ano"
      }
    },
    {
      "data": "12/11",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Dia Nacional do Supermercado",
      "visual": "Foto autorizada de mercado",
      "tela1": "Nosso reconhecimento a quem abastece a rotina das famílias.",
      "tela2": "O trabalho dos supermercados reúne compras, estoque, caixa e atendimento todos os dias.",
      "tela3": "Qual setor da operação mais exige organização?",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "12/11",
        "dia_semana": "quinta-feira",
        "tipo": "Reels",
        "ideia": "Antes de o produto chegar à cesta existe uma operação inteira",
        "producao": "Reel de 30 segundos · Mostrar uma sequência ilustrativa de compra, recebimento, estoque e atendimento. Concluir com homenagem e convite para conversar sobre gestão.",
        "legenda": "No Dia Nacional do Supermercado, valorizamos as equipes que abastecem a rotina das famílias. Organização acompanha cada etapa desse trabalho.",
        "chamada": "Conversar sobre a operação pelo link da bio.",
        "material": "Imagens autorizadas de mercado; só demonstrar módulos já confirmados pela equipe de produto."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "🛒 Dia do Supermercado",
        "desc": "Setor supermercadista"
      }
    },
    {
      "data": "13/11",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Gentileza no atendimento",
      "visual": "Vídeo encenado",
      "tela1": "Um atendimento gentil começa com atenção ao pedido.",
      "tela2": "Ouça, confirme o que foi entendido e explique o próximo passo.",
      "tela3": "Qual gesto simples faz diferença para seu cliente?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "14/11",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Revisão antes do pico",
      "visual": "Checklist curto",
      "tela1": "Você já percorreu o caminho de uma venda da sua campanha?",
      "tela2": "Confira o cadastro, a condição anunciada e a orientação passada à equipe.",
      "tela3": "O que ainda precisa ajustar antes do movimento aumentar?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "15/11",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Proclamação da República",
      "visual": "Arte institucional",
      "tela1": "15 de novembro. Uma data da história do Brasil.",
      "tela2": "Respeito, participação e responsabilidade ajudam a construir a vida em comunidade.",
      "tela3": "Bom domingo. Que seja um dia de reflexão e convivência.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "feriado_nacional",
        "badge": "🔴 Feriado Nacional: Proclamação da República",
        "desc": "Feriado Nacional"
      }
    },
    {
      "data": "16/11",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Compras finais",
      "visual": "Lista de reposição",
      "tela1": "Antes da última compra para a campanha, revise os saldos.",
      "tela2": "Confirme o prazo real de entrega e evite anunciar o que ainda não está disponível.",
      "tela3": "Sua reposição está confirmada? Sim / Aguardando.",
      "opcoes_enquete": [
        "Sim",
        "Aguardando"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "17/11",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Organização do balcão",
      "visual": "Bastidor autorizado",
      "tela1": "O cliente encontra informação clara no balcão?",
      "tela2": "Deixe condições e orientações acessíveis para facilitar o trabalho da equipe.",
      "tela3": "Qual pergunta se repete mais no seu atendimento?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "18/11",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Recebimentos",
      "visual": "Ilustração de venda e pagamento",
      "tela1": "Venda registrada e pagamento confirmado precisam ser conferidos.",
      "tela2": "Revise a rotina de acompanhamento dos recebimentos com a equipe responsável.",
      "tela3": "Onde está sua maior dúvida? Conferência / Organização.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "19/11",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Empreendedorismo feminino",
      "visual": "Foto ou depoimento autorizado",
      "tela1": "Hoje valorizamos as mulheres que empreendem.",
      "tela2": "Cada trajetória traz aprendizados que podem ajudar outras mulheres a dar o próximo passo.",
      "tela3": "Qual conselho você daria a quem está começando?",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "19/11",
        "dia_semana": "quinta-feira",
        "tipo": "Reels",
        "ideia": "Uma decisão que ajudou minha empresa a se organizar",
        "producao": "Reel de entrevista de 30 a 45 segundos · Perguntar a uma empreendedora: qual era a dificuldade, o que mudou no processo e o que aprendeu. Usar sua resposta real, sem atribuir resultado à Trudata sem evidência.",
        "legenda": "No Dia do Empreendedorismo Feminino, abrimos espaço para uma experiência real de quem empreende. Hoje, nosso reconhecimento às mulheres que constroem seus negócios.",
        "chamada": "Compartilhar um aprendizado.",
        "material": "Convidada e fala aprovadas. Se não houver entrevista, usar mensagem da equipe sem inventar personagem."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "👩‍💼 Empreendedorismo Feminino",
        "desc": "Mulheres empreendedoras"
      }
    },
    {
      "data": "20/11",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Consciência Negra",
      "visual": "Arte institucional",
      "tela1": "Dia Nacional de Zumbi e da Consciência Negra.",
      "tela2": "Respeito e enfrentamento ao racismo precisam fazer parte das relações de trabalho e atendimento.",
      "tela3": "Conheça e valorize negócios e profissionais negros da sua comunidade.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "20/11",
        "dia_semana": "sexta-feira",
        "tipo": "Post Estático",
        "ideia": "Respeito precisa fazer parte de todos os dias",
        "producao": "Post institucional · Arte com texto curto e legível; legenda sobre enfrentamento ao racismo nas relações. Publicar sem oferta, promoção ou chamada para demonstração.",
        "legenda": "O Dia Nacional de Zumbi e da Consciência Negra convida à memória e ao compromisso com relações mais justas. Respeito e enfrentamento ao racismo fazem parte dessa construção diária.",
        "chamada": "Leitura e reflexão, sem chamada comercial.",
        "material": "Revisão de linguagem; não atribuir programas de diversidade inexistentes à Trudata."
      },
      "ocasiao": {
        "tipo": "feriado_nacional",
        "badge": "✊ Consciência Negra",
        "desc": "Feriado Nacional"
      }
    },
    {
      "data": "21/11",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Perguntas da campanha",
      "visual": "Cartões de perguntas frequentes",
      "tela1": "Uma dúvida respondida antes pode facilitar o atendimento depois.",
      "tela2": "Prepare respostas claras sobre produtos e condições da campanha.",
      "tela3": "Qual resposta sua equipe precisa deixar pronta?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "22/11",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Semana da Black Friday",
      "visual": "Calendário",
      "tela1": "A Black Friday acontece nesta sexta-feira, dia 27.",
      "tela2": "Separe um momento para conferir estoque, preços e orientações finais.",
      "tela3": "Em uma palavra, como está a preparação da sua loja?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "23/11",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Revisão dos anúncios",
      "visual": "Arte de anúncio fictício",
      "tela1": "O anúncio está igual ao que sua operação consegue entregar?",
      "tela2": "Confira produtos, valores, condições e disponibilidade antes da publicação.",
      "tela3": "Peça a alguém da equipe para fazer a segunda conferência.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "24/11",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Alinhamento final",
      "visual": "Vídeo curto de reunião",
      "tela1": "Todo mundo sabe o que fazer durante a campanha?",
      "tela2": "Defina responsáveis por reposição, dúvidas, caixa e acompanhamento do movimento.",
      "tela3": "Qual função ainda precisa de um responsável?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "25/11",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Um passo de cada vez",
      "visual": "Apresentador",
      "tela1": "Preparar a operação também é reduzir dúvidas da equipe.",
      "tela2": "Revise o processo de venda já utilizado e mantenha as instruções acessíveis.",
      "tela3": "Qual rotina você quer revisar antes de sexta?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "26/11",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Véspera da Black Friday",
      "visual": "Checklist animado",
      "tela1": "É amanhã. Faça a última conferência com calma.",
      "tela2": "Confira os itens anunciados, as condições e os canais de atendimento.",
      "tela3": "Sua operação está pronta? Sim / Falta um ajuste.",
      "opcoes_enquete": [
        "Sim",
        "Falta um ajuste"
      ],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comercial",
        "badge": "🦃 Véspera Black Friday",
        "desc": "Alinhamento final da equipe"
      }
    },
    {
      "data": "27/11",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Black Friday",
      "visual": "Vídeo de incentivo",
      "tela1": "Bom trabalho a quem está na operação nesta Black Friday.",
      "tela2": "Acompanhe o movimento e registre os pontos que precisam de atenção.",
      "tela3": "Qual área está mais movimentada? Atendimento / Caixa / Estoque.",
      "opcoes_enquete": [
        "Atendimento",
        "Caixa",
        "Estoque"
      ],
      "tem_feed": true,
      "feed": {
        "data": "27/11",
        "dia_semana": "sexta-feira",
        "tipo": "Reels",
        "ideia": "Três conferências antes do movimento aumentar",
        "producao": "Reel de 20 a 30 segundos · Abrir com a Black Friday; mostrar conferência de produtos anunciados, condições de venda e orientações da equipe; terminar desejando bom trabalho.",
        "legenda": "A Black Friday chegou. Confira o que foi anunciado, alinhe a equipe e acompanhe a operação ao longo do dia. Bom trabalho a quem está no atendimento, no caixa e no estoque.",
        "chamada": "Salvar o checklist.",
        "material": "Conteúdo educativo. Não anunciar suporte especial, desconto ou capacidade técnica sem confirmação."
      },
      "ocasiao": {
        "tipo": "comercial",
        "badge": "🔥 Black Friday 2026",
        "desc": "Pico de varejo do ano"
      }
    },
    {
      "data": "28/11",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Depois do pico",
      "visual": "Gráfico ilustrativo",
      "tela1": "Como foi a Black Friday na sua empresa?",
      "tela2": "Reúna vendas, recebimentos e ocorrências para fazer uma leitura do resultado.",
      "tela3": "Qual aprendizado você levará para a próxima campanha?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "29/11",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Preparar o próximo passo",
      "visual": "Lista na tela",
      "tela1": "Antes de pensar em dezembro, revise o que ficou pendente.",
      "tela2": "Separe as ações que precisam de retorno e escolha quem vai acompanhá-las.",
      "tela3": "Qual será sua primeira tarefa na segunda-feira?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "30/11",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Cyber Monday e cuidado digital",
      "visual": "Apresentador",
      "tela1": "Hoje é Cyber Monday. Seu atendimento digital está organizado?",
      "tela2": "Revise os pedidos da campanha e confira remetentes antes de abrir links recebidos.",
      "tela3": "Quer conversar sobre sua operação digital? Responda CANAIS.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "30/11",
        "dia_semana": "segunda-feira",
        "tipo": "Carrossel",
        "ideia": "Cyber Monday com informação organizada",
        "producao": "Carrossel de 5 telas · 1: chamada. 2: conferir pedidos. 3: acompanhar saldos nos canais. 4: organizar retornos ao cliente. 5: avaliar a integração disponível para a operação.",
        "legenda": "Na Cyber Monday, a experiência do cliente também depende da informação que circula entre os canais. Revise pedidos, disponibilidade e atendimento com sua equipe.",
        "chamada": "Pedir uma conversa sobre integração.",
        "material": "Usar esquema ilustrativo; não afirmar que toda loja virtual é compatível com o ERP."
      },
      "ocasiao": {
        "tipo": "comercial",
        "badge": "💻 Cyber Monday & Seg. Informação",
        "desc": "Vendas digitais e segurança"
      }
    },
    {
      "data": "01/12",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Planejamento de dezembro",
      "visual": "Calendário e produtos",
      "tela1": "Dezembro começou. Como sua empresa vai organizar o fim do ano?",
      "tela2": "Distribua compras, atendimento e fechamento financeiro ao longo das semanas.",
      "tela3": "Qual é a maior prioridade do mês?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "campanha",
        "badge": "🎗️ Dezembro Vermelho",
        "desc": "Conscientização de saúde"
      }
    },
    {
      "data": "02/12",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Comunicação com o cliente",
      "visual": "Vídeo encenado",
      "tela1": "Uma resposta clara pode evitar uma conversa longa.",
      "tela2": "Explique o próximo passo e combine o retorno que sua equipe consegue cumprir.",
      "tela3": "Qual informação seu cliente mais precisa receber?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "03/12",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Dia da Pessoa com Deficiência",
      "visual": "Arte acessível",
      "tela1": "Acessibilidade também aparece nos detalhes do atendimento.",
      "tela2": "Revise legibilidade, legendas e a forma de orientar diferentes clientes.",
      "tela3": "Escolha uma barreira de comunicação para melhorar hoje.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "03/12",
        "dia_semana": "quinta-feira",
        "tipo": "Carrossel",
        "ideia": "Seu atendimento é fácil de entender",
        "producao": "Carrossel de 5 telas · 1: pergunta. 2: letras legíveis. 3: vídeos legendados. 4: instruções claras e escuta. 5: escolher uma melhoria prática.",
        "legenda": "No Dia Internacional das Pessoas com Deficiência, propomos uma revisão concreta: o que pode ficar mais acessível na comunicação da sua empresa?",
        "chamada": "Compartilhar com quem cuida do atendimento.",
        "material": "Bom contraste e linguagem respeitosa; não anunciar certificação de acessibilidade."
      },
      "ocasiao": {
        "tipo": "conscientizacao",
        "badge": "♿ Dia da Pessoa com Deficiência",
        "desc": "Acessibilidade no comércio"
      }
    },
    {
      "data": "04/12",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Campanha de Natal",
      "visual": "Storyboard de anúncio",
      "tela1": "Sua campanha de Natal já tem uma mensagem principal?",
      "tela2": "Escolha um benefício real para o cliente e use informações consistentes nos canais.",
      "tela3": "O que sua campanha quer destacar?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "05/12",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Dia do Voluntariado",
      "visual": "Foto autorizada ou arte",
      "tela1": "Ações locais ganham força quando mais pessoas participam.",
      "tela2": "Conheça uma iniciativa séria da sua comunidade e descubra como colaborar.",
      "tela3": "Que projeto da sua cidade merece ser conhecido?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "06/12",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Loja pronta para a semana",
      "visual": "Checklist",
      "tela1": "Antes de abrir a semana, confira os produtos de maior procura.",
      "tela2": "Reveja disponibilidade, preços e informações que ajudam no atendimento.",
      "tela3": "O que você vai conferir primeiro amanhã?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "07/12",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Reposição para o Natal",
      "visual": "Lista de compras",
      "tela1": "Seu próximo pedido considera o que ainda está em estoque?",
      "tela2": "Compare procura, saldo e prazo de entrega antes de confirmar a compra.",
      "tela3": "Qual categoria merece atenção nesta semana?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "08/12",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Dia da Família",
      "visual": "Arte ou equipe autorizada",
      "tela1": "Hoje celebramos os vínculos de cuidado e convivência.",
      "tela2": "Nosso carinho às famílias que fazem parte das histórias de clientes e colaboradores.",
      "tela3": "Que tradição de fim de ano é especial para você?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "👨‍👩‍👧 Dia da Família / N. Sra. Conceição",
        "desc": "Feriado em alguns municípios"
      }
    },
    {
      "data": "09/12",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Registros consistentes",
      "visual": "Tela demonstrativa",
      "tela1": "Uma rotina registrada fica mais fácil de acompanhar.",
      "tela2": "Confira se sua equipe sabe onde registrar cada informação importante da operação.",
      "tela3": "Qual registro costuma ficar para depois?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "10/12",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Direitos Humanos",
      "visual": "Arte institucional",
      "tela1": "Respeito à dignidade das pessoas cabe em todos os ambientes.",
      "tela2": "No trabalho e no atendimento, pratique escuta, inclusão e tratamento respeitoso.",
      "tela3": "Qual atitude sua empresa pode fortalecer todos os dias?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "conscientizacao",
        "badge": "⚖️ Direitos Humanos",
        "desc": "Dignidade e respeito no trabalho"
      }
    },
    {
      "data": "11/12",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Indicadores do mês",
      "visual": "Gráfico ilustrativo",
      "tela1": "O movimento de dezembro está dentro do que você esperava?",
      "tela2": "Compare os resultados por período e observe quais categorias merecem atenção.",
      "tela3": "Você já fez a primeira revisão do mês?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "12/12",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Campanha 12 12",
      "visual": "Arte de data dupla",
      "tela1": "Se o 12.12 faz parte da sua estratégia, confira a operação antes do anúncio.",
      "tela2": "Preço claro, disponibilidade e equipe orientada ajudam a manter a campanha organizada.",
      "tela3": "Seu foco hoje é: Divulgar / Atender / Repor.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "comercial",
        "badge": "🛍️ 12.12 Promoções",
        "desc": "Data promocional de varejo"
      }
    },
    {
      "data": "13/12",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Equipe preparada",
      "visual": "Vídeo curto",
      "tela1": "Como sua equipe acompanha as dúvidas de dezembro?",
      "tela2": "Reúna as perguntas mais frequentes e atualize as orientações de atendimento.",
      "tela3": "Qual dúvida apareceu mais nesta semana?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "14/12",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Compras e prazos",
      "visual": "Calendário de entregas",
      "tela1": "Ainda dá tempo de receber o que sua loja precisa?",
      "tela2": "Confirme os prazos com fornecedores e anuncie conforme a disponibilidade real.",
      "tela3": "Qual entrega você precisa acompanhar hoje?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "15/12",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Gestão que evoluiu",
      "visual": "Apresentador",
      "tela1": "Qual rotina da sua empresa ficou mais organizada em 2026?",
      "tela2": "Pode ser uma melhoria pequena que fez diferença para o trabalho de todos.",
      "tela3": "Conte para nós uma evolução deste ano.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "16/12",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Horários de fim de ano",
      "visual": "Arte com calendário",
      "tela1": "Sua empresa já definiu como será o atendimento nas festas?",
      "tela2": "Publique somente os horários confirmados e mantenha a informação fácil de encontrar.",
      "tela3": "Seu comunicado de fim de ano está pronto?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "17/12",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Dia do Bioma Pampa",
      "visual": "Foto identificada e autorizada do Pampa",
      "tela1": "Hoje é Dia do Bioma Pampa, parte importante do patrimônio natural e cultural gaúcho.",
      "tela2": "Conhecer e valorizar suas paisagens também é cuidar da nossa relação com o Rio Grande do Sul.",
      "tela3": "Que paisagem do nosso estado tem um significado especial para você?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "regional_rs",
        "badge": "🌾 Dia do Bioma Pampa",
        "desc": "Patrimônio natural e cultural do RS"
      }
    },
    {
      "data": "18/12",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Estoque da semana final",
      "visual": "Tela demonstrativa validada",
      "tela1": "Quais produtos precisam de atenção antes da semana de Natal?",
      "tela2": "Confira os saldos dos itens mais procurados e organize a reposição possível.",
      "tela3": "Qual categoria você vai revisar hoje?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "19/12",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Apoio à equipe",
      "visual": "Vídeo de colaborador",
      "tela1": "Um agradecimento também cabe nos dias mais corridos.",
      "tela2": "Reconheça o esforço da equipe e alinhe as prioridades do atendimento.",
      "tela3": "Quem você quer agradecer pelo trabalho desta semana?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "20/12",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Dia do Mecânico",
      "visual": "Ordem de serviço fictícia",
      "tela1": "Nosso reconhecimento aos profissionais da mecânica.",
      "tela2": "Na oficina, registrar a solicitação e acompanhar o serviço ajuda a organizar o trabalho.",
      "tela3": "Qual etapa da sua oficina mais precisa de organização?",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "20/12",
        "dia_semana": "domingo",
        "tipo": "Reels",
        "ideia": "Cada serviço tem uma história que precisa ser registrada",
        "producao": "Reel de 30 segundos · Usar solicitação fictícia de oficina; mostrar identificação, descrição do pedido e acompanhamento da ordem de serviço. Encerrar agradecendo aos mecânicos.",
        "legenda": "No Dia do Mecânico, nosso reconhecimento a quem cuida de cada detalhe do serviço. Uma rotina registrada ajuda a equipe a acompanhar o trabalho e orientar o cliente.",
        "chamada": "Solicitar demonstração para prestação de serviços.",
        "material": "Ambiente de teste; confirmar telas e caminhos atuais do módulo antes de gravar."
      },
      "ocasiao": {
        "tipo": "comemorativa",
        "badge": "🔧 Dia do Mecânico",
        "desc": "Oficinas mecânicas e ordem de serviço"
      }
    },
    {
      "data": "21/12",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Chegada do verão",
      "visual": "Foto de coleção ou produtos",
      "tela1": "O verão começa hoje à noite. A procura da sua loja pode mudar.",
      "tela2": "Observe o histórico da estação e acompanhe os itens que ganham movimento.",
      "tela3": "Qual produto costuma ter mais saída no verão?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "sazonal",
        "badge": "☀️ Início do Verão",
        "desc": "Mudança de estação"
      }
    },
    {
      "data": "22/12",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Atendimento de última hora",
      "visual": "Vídeo encenado",
      "tela1": "O cliente chegou com pressa. A informação precisa estar clara.",
      "tela2": "Confirme disponibilidade e explique as condições antes de concluir o atendimento.",
      "tela3": "Qual orientação sua equipe precisa reforçar hoje?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "23/12",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Comunicação antes do Natal",
      "visual": "Agenda visual",
      "tela1": "Falta pouco para o Natal. Relembre os horários já confirmados.",
      "tela2": "Confira também quem acompanha pedidos e dúvidas pendentes.",
      "tela3": "A informação está visível nos seus canais?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "24/12",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Véspera de Natal",
      "visual": "Vídeo curto da equipe",
      "tela1": "Nesta véspera de Natal, nosso agradecimento a quem esteve conosco.",
      "tela2": "Que seja um momento de cuidado e proximidade com as pessoas importantes para você.",
      "tela3": "Receba o carinho da equipe Trudata.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": {
        "tipo": "ponto_facultativo",
        "badge": "🎄 Véspera de Natal",
        "desc": "Ponto facultativo após 13h"
      }
    },
    {
      "data": "25/12",
      "ano": "2026",
      "dia_semana": "sexta-feira",
      "tema": "Natal",
      "visual": "Arte institucional",
      "tela1": "Feliz Natal, de toda a equipe Trudata.",
      "tela2": "Desejamos paz, acolhimento e bons momentos a clientes, parceiros e colaboradores.",
      "tela3": "Obrigado por fazer parte da nossa história.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "25/12",
        "dia_semana": "sexta-feira",
        "tipo": "Post Estático",
        "ideia": "Feliz Natal da equipe Trudata",
        "producao": "Post estático · Arte com mensagem central e identidade da empresa; foto da equipe é alternativa se autorizada. Manter leitura simples e sem oferta comercial.",
        "legenda": "Desejamos um Natal de paz, acolhimento e bons momentos. Obrigado a clientes, parceiros e colaboradores por fazerem parte da nossa história.",
        "chamada": "Sem chamada comercial.",
        "material": "Arte própria; assinatura Trudata; publicação às 8h."
      },
      "ocasiao": {
        "tipo": "feriado_nacional",
        "badge": "🎅 Natal (Feriado Nacional)",
        "desc": "Mensagem institucional calorosa"
      }
    },
    {
      "data": "26/12",
      "ano": "2026",
      "dia_semana": "sábado",
      "tema": "Depois do Natal",
      "visual": "Lista leve",
      "tela1": "Quando sua operação retomar, reserve um momento para revisar as pendências.",
      "tela2": "Organize os retornos ao cliente e os registros que precisam ser conferidos.",
      "tela3": "Qual tarefa ficará no topo da sua lista?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "27/12",
      "ano": "2026",
      "dia_semana": "domingo",
      "tema": "Aprendizados de dezembro",
      "visual": "Caixa de perguntas",
      "tela1": "O que dezembro ensinou sobre a rotina da sua empresa?",
      "tela2": "Anote um acerto e uma melhoria para levar ao próximo ano.",
      "tela3": "Quer compartilhar um aprendizado com a gente?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "28/12",
      "ano": "2026",
      "dia_semana": "segunda-feira",
      "tema": "Preparar o fechamento",
      "visual": "Checklist",
      "tela1": "A última semana do ano chegou.",
      "tela2": "Confira pendências de estoque, documentos e financeiro com cada responsável.",
      "tela3": "Qual frente precisa de mais atenção no fechamento?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "29/12",
      "ano": "2026",
      "dia_semana": "terça-feira",
      "tema": "Prioridade para 2027",
      "visual": "Apresentador",
      "tela1": "Se você pudesse melhorar uma rotina em 2027, qual escolheria?",
      "tela2": "Uma meta específica ajuda a definir o próximo passo e quem vai acompanhá-lo.",
      "tela3": "Sua prioridade é: Estoque / Financeiro / Atendimento.",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "30/12",
      "ano": "2026",
      "dia_semana": "quarta-feira",
      "tema": "Agradecimento aos clientes",
      "visual": "Montagem autorizada da equipe",
      "tela1": "2026 também foi feito das conversas que tivemos com nossos clientes.",
      "tela2": "Obrigado pela confiança e por compartilhar os desafios da sua empresa.",
      "tela3": "Qual conteúdo da Trudata você quer ver mais em 2027?",
      "opcoes_enquete": [],
      "tem_feed": false,
      "feed": null,
      "ocasiao": null
    },
    {
      "data": "31/12",
      "ano": "2026",
      "dia_semana": "quinta-feira",
      "tema": "Encerramento do ano",
      "visual": "Vídeo institucional",
      "tela1": "Obrigado por caminhar com a Trudata em 2026.",
      "tela2": "Desejamos um novo ano com saúde, boas relações e planos que possam sair do papel.",
      "tela3": "Feliz 2027. Nos vemos no próximo ano.",
      "opcoes_enquete": [],
      "tem_feed": true,
      "feed": {
        "data": "31/12",
        "dia_semana": "quinta-feira",
        "tipo": "Reels",
        "ideia": "Obrigado por fazer parte de 2026",
        "producao": "Reel de 30 a 40 segundos · Organizar registros reais de equipe, trabalho e encontros. Cada trecho recebe uma frase curta. Finalizar com votos para 2027.",
        "legenda": "Encerramos 2026 com gratidão pelas relações construídas e pelas conversas que tivemos ao longo do ano. Desejamos saúde e bons caminhos para 2027.",
        "chamada": "Contar qual conteúdo deseja acompanhar no próximo ano.",
        "material": "Usar apenas acontecimentos reais; métricas e resultados só entram com fonte e aprovação."
      },
      "ocasiao": {
        "tipo": "ponto_facultativo",
        "badge": "🥂 Véspera de Ano Novo",
        "desc": "Retrospectiva 2026 e boas-vindas a 2027"
      }
    }
  ],
  "feed_reels": {
    "15/09": {
      "data": "15/09",
      "dia_semana": "terça-feira",
      "tipo": "Reels",
      "ideia": "Obrigado por compartilhar sua rotina com a Trudata",
      "producao": "Reel de 25 a 35 segundos · 0–4s: equipe agradece. 4–20s: três colaboradores contam o tipo de necessidade que escutam, sem citar clientes. 20–30s: convite para o público compartilhar uma dificuldade.",
      "legenda": "Hoje nosso agradecimento vai para quem confia na Trudata e divide com a gente os desafios da sua empresa. Qual rotina você gostaria de simplificar?",
      "chamada": "Responder nos comentários.",
      "material": "Vídeos da equipe; legendas; nenhum depoimento ou resultado inventado."
    },
    "20/09": {
      "data": "20/09",
      "dia_semana": "domingo",
      "tipo": "Reels",
      "ideia": "De Sarandi para as histórias do comércio gaúcho",
      "producao": "Reel de 20 a 30 segundos · Abrir com referência a Sarandi; mostrar equipe e registros locais autorizados; terminar com mensagem de valorização da cultura e das pessoas do RS.",
      "legenda": "Neste 20 de setembro, celebramos nossas raízes e as pessoas que fazem o Rio Grande do Sul acontecer. Um abraço da equipe Trudata a todas as cidades que caminham conosco.",
      "chamada": "Comentar a cidade de onde acompanha a empresa.",
      "material": "Imagens próprias; referências regionais sem caricatura; evitar sugerir parceria com eventos."
    },
    "22/09": {
      "data": "22/09",
      "dia_semana": "terça-feira",
      "tipo": "Carrossel",
      "ideia": "Uma boa parceria com a contabilidade começa na rotina",
      "producao": "Carrossel de 5 telas · 1: homenagem. 2: organizar documentos. 3: combinar periodicidade de envio. 4: conferir pendências com o contador. 5: agradecimento e convite para compartilhar.",
      "legenda": "No Dia do Contador, reconhecemos quem acompanha decisões importantes das empresas. Organização e comunicação ajudam essa parceria a funcionar melhor todos os dias.",
      "chamada": "Compartilhar com o contador.",
      "material": "Arte simples; não ensinar regra fiscal nem anunciar prazo de obrigação."
    },
    "25/09": {
      "data": "25/09",
      "dia_semana": "sexta-feira",
      "tipo": "Reels",
      "ideia": "Nosso reconhecimento a quem cuida com responsabilidade",
      "producao": "Reel de 20 a 30 segundos · Abrir com homenagem; mostrar profissional autorizado ou equipe fazendo o agradecimento; concluir sem demonstração de medicamento ou promessa clínica.",
      "legenda": "No Dia Mundial do Farmacêutico, promovido pela FIP, nosso reconhecimento a quem dedica conhecimento e responsabilidade ao cuidado com as pessoas.",
      "chamada": "Deixar uma mensagem de reconhecimento.",
      "material": "Autorização do participante; arte própria; não utilizar a identidade oficial da campanha como anúncio comercial."
    },
    "05/10": {
      "data": "05/10",
      "dia_semana": "segunda-feira",
      "tipo": "Reels",
      "ideia": "Qual rotina do seu pequeno negócio precisa se organizar primeiro",
      "producao": "Reel de 30 segundos · Mostrar três situações encenadas: documentos espalhados, busca de informação e dúvida sobre emissão. Apresentar o Easy como solução web divulgada pela Trudata; convidar para avaliar aderência.",
      "legenda": "No Dia da Micro e Pequena Empresa, valorizamos quem empreende todos os dias. Se organizar a emissão fiscal é uma prioridade, conheça a proposta do Trudata Easy e converse com nossa equipe.",
      "chamada": "Solicitar uma demonstração pelo link da bio.",
      "material": "Captura de demonstração validada do Easy; confirmar condições de contratação antes de incluí-las."
    },
    "12/10": {
      "data": "12/10",
      "dia_semana": "segunda-feira",
      "tipo": "Post Estático",
      "ideia": "Um dia para valorizar a infância",
      "producao": "Post estático · Ilustração original de brincadeiras; frase principal curta; legenda acolhedora. Evitar usar criança como porta-voz comercial.",
      "legenda": "Que toda criança tenha espaço para brincar, aprender e imaginar. A equipe Trudata deseja um Dia das Crianças com cuidado e bons momentos.",
      "chamada": "Compartilhar uma lembrança de infância, se desejar.",
      "material": "Preferir ilustração; se houver fotos de menores, obter autorização dos responsáveis."
    },
    "19/10": {
      "data": "19/10",
      "dia_semana": "segunda-feira",
      "tipo": "Reels",
      "ideia": "Toda melhoria começa com uma pergunta",
      "producao": "Reel de 30 a 40 segundos · 0–5s: qual tarefa dá trabalho. 5–15s: equipe entende a necessidade. 15–30s: bastidor de teste de rotina já existente. Final: valorização dos profissionais de tecnologia.",
      "legenda": "No Dia Nacional da Inovação, mostramos o valor de entender a rotina antes de propor uma solução. Nosso reconhecimento aos profissionais de TI que participam desse trabalho.",
      "chamada": "Comentar uma tarefa que gostaria de simplificar.",
      "material": "Bastidores reais; não apresentar rotina existente como lançamento nem prometer recurso futuro."
    },
    "30/10": {
      "data": "30/10",
      "dia_semana": "sexta-feira",
      "tipo": "Reels",
      "ideia": "Quem faz o comércio acontecer",
      "producao": "Reel de 20 a 30 segundos · Sequência de funções: atendimento, organização, reposição e caixa. Cada pessoa aparece por alguns segundos; finalizar com agradecimento coletivo.",
      "legenda": "Hoje nosso reconhecimento vai a quem trabalha no comércio e cuida de tantos detalhes para atender bem. Feliz Dia do Comerciário.",
      "chamada": "Marcar um colega, se desejar.",
      "material": "Equipe ou clientes com autorização; não prometer alteração do funcionamento na data."
    },
    "12/11": {
      "data": "12/11",
      "dia_semana": "quinta-feira",
      "tipo": "Reels",
      "ideia": "Antes de o produto chegar à cesta existe uma operação inteira",
      "producao": "Reel de 30 segundos · Mostrar uma sequência ilustrativa de compra, recebimento, estoque e atendimento. Concluir com homenagem e convite para conversar sobre gestão.",
      "legenda": "No Dia Nacional do Supermercado, valorizamos as equipes que abastecem a rotina das famílias. Organização acompanha cada etapa desse trabalho.",
      "chamada": "Conversar sobre a operação pelo link da bio.",
      "material": "Imagens autorizadas de mercado; só demonstrar módulos já confirmados pela equipe de produto."
    },
    "19/11": {
      "data": "19/11",
      "dia_semana": "quinta-feira",
      "tipo": "Reels",
      "ideia": "Uma decisão que ajudou minha empresa a se organizar",
      "producao": "Reel de entrevista de 30 a 45 segundos · Perguntar a uma empreendedora: qual era a dificuldade, o que mudou no processo e o que aprendeu. Usar sua resposta real, sem atribuir resultado à Trudata sem evidência.",
      "legenda": "No Dia do Empreendedorismo Feminino, abrimos espaço para uma experiência real de quem empreende. Hoje, nosso reconhecimento às mulheres que constroem seus negócios.",
      "chamada": "Compartilhar um aprendizado.",
      "material": "Convidada e fala aprovadas. Se não houver entrevista, usar mensagem da equipe sem inventar personagem."
    },
    "20/11": {
      "data": "20/11",
      "dia_semana": "sexta-feira",
      "tipo": "Post Estático",
      "ideia": "Respeito precisa fazer parte de todos os dias",
      "producao": "Post institucional · Arte com texto curto e legível; legenda sobre enfrentamento ao racismo nas relações. Publicar sem oferta, promoção ou chamada para demonstração.",
      "legenda": "O Dia Nacional de Zumbi e da Consciência Negra convida à memória e ao compromisso com relações mais justas. Respeito e enfrentamento ao racismo fazem parte dessa construção diária.",
      "chamada": "Leitura e reflexão, sem chamada comercial.",
      "material": "Revisão de linguagem; não atribuir programas de diversidade inexistentes à Trudata."
    },
    "27/11": {
      "data": "27/11",
      "dia_semana": "sexta-feira",
      "tipo": "Reels",
      "ideia": "Três conferências antes do movimento aumentar",
      "producao": "Reel de 20 a 30 segundos · Abrir com a Black Friday; mostrar conferência de produtos anunciados, condições de venda e orientações da equipe; terminar desejando bom trabalho.",
      "legenda": "A Black Friday chegou. Confira o que foi anunciado, alinhe a equipe e acompanhe a operação ao longo do dia. Bom trabalho a quem está no atendimento, no caixa e no estoque.",
      "chamada": "Salvar o checklist.",
      "material": "Conteúdo educativo. Não anunciar suporte especial, desconto ou capacidade técnica sem confirmação."
    },
    "30/11": {
      "data": "30/11",
      "dia_semana": "segunda-feira",
      "tipo": "Carrossel",
      "ideia": "Cyber Monday com informação organizada",
      "producao": "Carrossel de 5 telas · 1: chamada. 2: conferir pedidos. 3: acompanhar saldos nos canais. 4: organizar retornos ao cliente. 5: avaliar a integração disponível para a operação.",
      "legenda": "Na Cyber Monday, a experiência do cliente também depende da informação que circula entre os canais. Revise pedidos, disponibilidade e atendimento com sua equipe.",
      "chamada": "Pedir uma conversa sobre integração.",
      "material": "Usar esquema ilustrativo; não afirmar que toda loja virtual é compatível com o ERP."
    },
    "03/12": {
      "data": "03/12",
      "dia_semana": "quinta-feira",
      "tipo": "Carrossel",
      "ideia": "Seu atendimento é fácil de entender",
      "producao": "Carrossel de 5 telas · 1: pergunta. 2: letras legíveis. 3: vídeos legendados. 4: instruções claras e escuta. 5: escolher uma melhoria prática.",
      "legenda": "No Dia Internacional das Pessoas com Deficiência, propomos uma revisão concreta: o que pode ficar mais acessível na comunicação da sua empresa?",
      "chamada": "Compartilhar com quem cuida do atendimento.",
      "material": "Bom contraste e linguagem respeitosa; não anunciar certificação de acessibilidade."
    },
    "20/12": {
      "data": "20/12",
      "dia_semana": "domingo",
      "tipo": "Reels",
      "ideia": "Cada serviço tem uma história que precisa ser registrada",
      "producao": "Reel de 30 segundos · Usar solicitação fictícia de oficina; mostrar identificação, descrição do pedido e acompanhamento da ordem de serviço. Encerrar agradecendo aos mecânicos.",
      "legenda": "No Dia do Mecânico, nosso reconhecimento a quem cuida de cada detalhe do serviço. Uma rotina registrada ajuda a equipe a acompanhar o trabalho e orientar o cliente.",
      "chamada": "Solicitar demonstração para prestação de serviços.",
      "material": "Ambiente de teste; confirmar telas e caminhos atuais do módulo antes de gravar."
    },
    "25/12": {
      "data": "25/12",
      "dia_semana": "sexta-feira",
      "tipo": "Post Estático",
      "ideia": "Feliz Natal da equipe Trudata",
      "producao": "Post estático · Arte com mensagem central e identidade da empresa; foto da equipe é alternativa se autorizada. Manter leitura simples e sem oferta comercial.",
      "legenda": "Desejamos um Natal de paz, acolhimento e bons momentos. Obrigado a clientes, parceiros e colaboradores por fazerem parte da nossa história.",
      "chamada": "Sem chamada comercial.",
      "material": "Arte própria; assinatura Trudata; publicação às 8h."
    },
    "31/12": {
      "data": "31/12",
      "dia_semana": "quinta-feira",
      "tipo": "Reels",
      "ideia": "Obrigado por fazer parte de 2026",
      "producao": "Reel de 30 a 40 segundos · Organizar registros reais de equipe, trabalho e encontros. Cada trecho recebe uma frase curta. Finalizar com votos para 2027.",
      "legenda": "Encerramos 2026 com gratidão pelas relações construídas e pelas conversas que tivemos ao longo do ano. Desejamos saúde e bons caminhos para 2027.",
      "chamada": "Contar qual conteúdo deseja acompanhar no próximo ano.",
      "material": "Usar apenas acontecimentos reais; métricas e resultados só entram com fonte e aprovação."
    }
  },
  "festivais_regionais": [
    {
      "nome": "Festejos Farroupilhas (RS)",
      "inicio": "15/09",
      "fim": "20/09",
      "cor": "emerald"
    },
    {
      "nome": "Oktoberfest Santa Cruz do Sul",
      "inicio": "08/10",
      "fim": "25/10",
      "cor": "amber"
    },
    {
      "nome": "Oktoberfest Igrejinha",
      "inicio": "09/10",
      "fim": "18/10",
      "cor": "yellow"
    },
    {
      "nome": "Natal Luz de Gramado",
      "inicio": "22/10",
      "fim": "31/12",
      "cor": "rose"
    }
  ]
};
