/* Rotina comercial: dados compartilhados, ações explícitas, sem envios automáticos. */
(() => {
'use strict';
const $=id=>document.getElementById(id), mode=document.body.dataset.commercial;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const digits=v=>String(v??'').replace(/\D/g,'');
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const dateText=v=>v?v.slice(0,10).split('-').reverse().join('/'):'Sem data';
let data, selected='', query='', listFilter='all', stops=[], preview=null, busy=false, timer, proposalView=null;
let metricsStart='',metricsEnd='',visitDay=today(),visitOrigin='Sarandi, RS';
function captureVisits(){if($('visit-day')){visitDay=$('visit-day').value;visitOrigin=$('visit-origin').value;stops.forEach((s,i)=>{if($('hour-'+i))s.hora=$('hour-'+i).value;});}}
const intro={enderecos:'Confira o endereço antes da próxima visita.',visitas:'Uma agenda possível, com empresas que já têm um ponto no mapa.',contatos:'Retome cada conversa com contexto e um próximo passo.',propostas:'Escopo, investimento e condições em um documento para negociar.',resultados:'O que foi registrado pela equipe, do contato ao aceite.'};
$('intro').textContent=intro[mode];
document.querySelectorAll('.commercial-nav a').forEach(a=>{if(a.pathname===location.pathname)a.setAttribute('aria-current','page');});
const field=(id,label,value='',type='text',extra='')=>`<label class="field">${label}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const area=(id,label,value='')=>`<label class="field wide">${label}<textarea id="${id}" maxlength="6000">${esc(value)}</textarea></label>`;
const button=(action,label,extra='')=>`<button class="btn" type="button" data-action="${action}" ${extra}>${label}</button>`;
const empty=text=>`<p class="empty-invite">${text}</p>`;
const name=p=>p?.empresa||p?.nome||'Cliente não encontrado';
const customer=id=>data.clientes.find(p=>p.id===id)||data.leads.find(p=>p.id===id);
const current=()=>customer(selected);
const located=p=>p.geolocalizacao?.status==='localizado';
function toast(message){$('notice').textContent=message;$('notice').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('notice').hidden=true,3500);}
function error(e){$('feedback').textContent=e.message||String(e);$('feedback').hidden=false;}
async function api(path,body){const r=await fetch('/api/comercial/'+path,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok||!d.sucesso)throw new Error(d.erro||'Não foi possível carregar. Confira o servidor e tente novamente.');return d;}
async function load(){data=await api('dados');if(!selected){const params=new URLSearchParams(location.search);const found=data.clientes.find(p=>(params.get('cnpj')&&digits(p.cnpj)===digits(params.get('cnpj')))||(params.get('cliente')&&norm(p.nome)===norm(params.get('cliente'))));selected=found?.id||'';}render();}
async function save(path,body,message){await api(path,body);await load();toast(message);}
function numbers(items){$('numbers').innerHTML=items.map(([n,l])=>`<div><strong>${esc(n)}</strong><span>${esc(l)}</span></div>`).join('');}
function due(id){const r=data.registros.contatos[id];return !r?.data?'semdata':r.data<today()?'atrasado':r.data===today()?'hoje':'futuro';}
function pool(){let items=mode==='contatos'?data.leads:data.clientes;if(mode==='enderecos')items=items.filter(p=>!located(p));if(mode==='visitas')items=items.filter(located);if(mode==='contatos'&&listFilter!=='all')items=items.filter(p=>due(p.id)===listFilter);return items.filter(p=>norm([name(p),p.cidade,p.cnpj,p.endereco].join(' ')).includes(norm(query)));}
function renderList(){const list=pool();$('client-list').innerHTML=list.slice(0,100).map(p=>`<button type="button" data-select="${esc(p.id)}" aria-pressed="${selected===p.id}"><strong>${esc(name(p))}</strong><small>${esc(p.cidade)}${mode==='contatos'?' · '+esc(data.registros.contatos[p.id]?.data?dateText(data.registros.contatos[p.id].data):'Sem retorno marcado'):''}</small></button>`).join('')||empty('Nenhum cadastro nesta busca. Altere o nome ou o filtro.');$('list-count').textContent=`${list.length} cadastros · ${Math.min(100,list.length)} exibidos`;}
function render(){
 if(mode==='resultados'){renderMetrics();return;}
 const local=data.clientes.filter(located).length;
 if(mode==='enderecos')numbers([[data.clientes.length-local,'Endereços pendentes'],[local,'Localizados no radar']]);
 if(mode==='visitas')numbers([[local,'Empresas localizadas'],[data.registros.visitas.length,'Agendas salvas'],[data.registros.eventos.filter(e=>e.tipo==='visita').length,'Visitas realizadas']]);
 if(mode==='contatos')numbers([[data.leads.filter(p=>due(p.id)==='atrasado').length,'Retornos atrasados'],[data.leads.filter(p=>due(p.id)==='hoje').length,'Retornos para hoje'],[data.leads.filter(p=>due(p.id)==='semdata').length,'Sem próxima data']]);
 if(mode==='propostas')numbers([[data.registros.propostas.length,'Propostas salvas'],[data.registros.propostas.filter(p=>p.status==='apresentada').length,'Em negociação'],[data.registros.propostas.filter(p=>p.status==='aceita').length,'Aceites registrados']]);
 $('app').innerHTML=`<div class="commercial-split"><aside><label class="field">Buscar ${mode==='contatos'?'no CRM':'no radar'}<input id="client-search" type="search" value="${esc(query)}" placeholder="Empresa, cidade ou CNPJ"></label>${mode==='contatos'?'<label class="field">Exibir<select id="due-filter"><option value="all">Todos os contatos</option><option value="hoje">Para hoje</option><option value="atrasado">Atrasados</option><option value="futuro">Próximos dias</option><option value="semdata">Sem retorno marcado</option></select></label>':''}<p class="small muted" id="list-count"></p><div id="client-list" class="commercial-list"></div>${mode==='contatos'?'<a href="radar_clientes.html">Adicionar empresas pelo radar</a>':''}</aside><article class="commercial-panel" id="panel"></article></div>`;
 $('client-search').oninput=e=>{query=e.target.value;renderList();};if($('due-filter')){$('due-filter').value=listFilter;$('due-filter').onchange=e=>{listFilter=e.target.value;renderList();};}renderList();renderPanel();
}
function renderPanel(){preview=null;const p=current();const panel=$('panel');
 if(mode==='visitas'){renderVisits();return;}
 if(mode==='propostas'){renderProposal();return;}
 if(!p){panel.innerHTML=empty('Escolha uma empresa na lista para começar.');return;}
 if(mode==='enderecos'){
 panel.innerHTML=`<h2>${esc(name(p))}</h2><p class="status-line">${esc(p.geolocalizacao?.observacao||'Localização pendente.')}</p><form id="edit-form"><div class="input-grid">${field('endereco','Rua e número',p.endereco,'text','required maxlength="300"')}${field('cidade','Cidade',p.cidade,'text','required maxlength="100"')}${field('uf','UF',p.uf||'RS','text','required pattern="RS" maxlength="2"')}${field('cep','CEP',p.cep,'text','maxlength="10"')}</div><p class="small">A consulta envia apenas o endereço à Geoapify. O ponto só muda depois de aplicar a correção.</p><button class="btn primary" type="submit">Consultar endereço</button></form><div id="geo-results"></div>`;
 $('edit-form').oninput=()=>{preview=null;$('geo-results').innerHTML='';};$('edit-form').onsubmit=e=>{e.preventDefault();run(async()=>{const body={id:p.id,...Object.fromEntries(['endereco','cidade','uf','cep'].map(k=>[k,$(k).value]))};const result=await api('consultar-endereco',body);if(['endereco','cidade','uf','cep'].some(k=>body[k]!==$(k).value))throw new Error('O endereço foi editado durante a consulta. Consulte novamente.');preview=result;$('geo-results').innerHTML=result.resultados.map((r,i)=>`<div class="review-result"><h3>${esc(r.endereco||'Sem endereço completo')}</h3><p>${esc(r.motivo||'Rua, número, cidade e posição do prédio compatíveis.')}</p>${!r.motivo?`<label class="confirmed-label"><input type="checkbox" id="confirm-${i}">Conferi que este endereço corresponde à empresa ou filial.</label>${button('apply-address','Aplicar endereço',`data-index="${i}"`)}`:''}</div>`).join('')||empty('Nenhum resultado encontrado. Revise rua, número e cidade e consulte novamente.');});};
 }else if(mode==='contatos'){
 const rec=data.registros.contatos[p.id]||{};panel.innerHTML=`<h2>${esc(name(p))}</h2><p>${esc(p.nome||'')} · ${esc(p.cidade||'')}</p><h3>Última conversa registrada</h3><p>${rec.ultima_data?dateText(rec.ultima_data)+' · '+esc(rec.ultima_nota):'Nenhuma conversa registrada nesta ferramenta.'}</p><details><summary>Notas do cadastro</summary><p>${esc(p.notas||'Sem notas.')}</p></details><form id="contact-form"><div class="input-grid">${field('next-date','Próximo retorno',rec.data||'','date')}${field('next-action','Próxima ação combinada',rec.acao||'','text','maxlength="1000"')}${area('contact-note','O que aconteceu na conversa?')}</div><label class="confirmed-label"><input id="contact-done" type="checkbox">Registrar contato realizado agora</label><button class="btn primary" type="submit">Salvar acompanhamento</button></form><div class="actions"><a class="btn" href="${esc('cadencia_sdr.html?'+new URLSearchParams({cliente:name(p),cidade:p.cidade||'',decisor:p.nome||''}))}">Preparar uma mensagem</a></div><section><h3>Histórico de conversas</h3>${data.registros.eventos.filter(e=>e.tipo==='contato'&&e.cliente_id===p.id).slice().reverse().map(e=>`<div class="record"><strong>${dateText(e.data)}</strong><p>${esc(e.detalhes)}</p></div>`).join('')||empty('Registre o primeiro contato para acompanhar a evolução.')}</section>`;
 $('contact-form').onsubmit=e=>{e.preventDefault();run(()=>save('salvar-contato',{id:p.id,data:$('next-date').value,acao:$('next-action').value,nota:$('contact-note').value,realizado:$('contact-done').checked},'Acompanhamento salvo'));};
 }
}
function routeLinks(plan){const coords=s=>{const p=customer(s.id);return `${p.lat},${p.lon}`;};let links=[];for(let i=0;i<plan.paradas.length;i+=4){const group=plan.paradas.slice(i,i+4),params=new URLSearchParams({api:'1',origin:i?coords(plan.paradas[i-1]):plan.origem,destination:coords(group.at(-1)),travelmode:'driving'});if(group.length>1)params.set('waypoints',group.slice(0,-1).map(coords).join('|'));links.push(`<a class="btn" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?${esc(params.toString())}">Abrir trajeto${plan.paradas.length>4?' · trecho '+(i/4+1):''}</a>`);}return links.join('');}
function renderVisits(){
 const p=current();$('panel').innerHTML=`<h2>Agenda de visitas</h2><p>Escolha até oito empresas. Defina a ordem e os horários; o trajeto abre no Google Maps.</p>${p?`<div class="review-result"><strong>${esc(name(p))}</strong><p>${esc(p.endereco)} · ${esc(p.cidade)}</p>${button('add-stop','Adicionar à agenda')}</div>`:''}<form id="visit-form"><div class="input-grid">${field('visit-day','Dia das visitas',visitDay,'date','required')}${field('visit-origin','Ponto de partida',visitOrigin,'text','required maxlength="300"')}</div><ol>${stops.map((s,i)=>`<li><strong>${esc(name(customer(s.id)))}</strong>${field('hour-'+i,'Horário da visita '+(i+1),s.hora,'time','required')}<div class="actions">${i?button('up-stop','Mover para cima',`data-index="${i}"`):''}${button('remove-stop','Remover',`data-index="${i}"`)}</div></li>`).join('')}</ol>${!stops.length?empty('Selecione uma empresa na lista e adicione a primeira visita.'):'<button class="btn primary" type="submit">Salvar agenda</button>'}</form><section><h3>Agendas salvas</h3>${data.registros.visitas.slice().sort((a,b)=>b.data.localeCompare(a.data)).map(plan=>`<div class="record"><h3>${dateText(plan.data)}</h3><p>Saída: ${esc(plan.origem)}</p><ol>${plan.paradas.map(s=>`<li>${esc(s.hora)} · ${esc(name(customer(s.id)))} ${s.concluida?'<strong>Visitado</strong>':button('finish-visit','Registrar visita realizada',`data-plan="${plan.id}" data-id="${esc(s.id)}"`)}</li>`).join('')}</ol><div class="actions">${routeLinks(plan)}</div></div>`).join('')||empty('Salve a primeira agenda para organizar as visitas da equipe.')}</section>`;
 $('visit-form').onsubmit=e=>{e.preventDefault();run(async()=>{const body={data:$('visit-day').value,origem:$('visit-origin').value,paradas:stops.map((s,i)=>({id:s.id,hora:$('hour-'+i).value}))};await api('salvar-visita',body);stops=[];await load();toast('Agenda salva');});};
}
let proposalEdit='',conditionsDraft='',validDraft=today();
let items=[{descricao:'Licença e suporte ERP',tipo:'mensal',valor:''},{descricao:'Implantação e treinamento',tipo:'unico',valor:''}];
function proposalText(p){const monthly=p.itens.filter(i=>i.tipo==='mensal').reduce((a,i)=>a+Number(i.valor),0),one=p.itens.filter(i=>i.tipo==='unico').reduce((a,i)=>a+Number(i.valor),0);return `PROPOSTA COMERCIAL · TRUDATA\n${p.empresa}\nCNPJ: ${p.cnpj||'Não informado'}\n${p.endereco||''}\nVálida até ${dateText(p.validade)}\n\nServiços\n${p.itens.map(i=>`${i.descricao}: ${money(i.valor)} (${i.tipo==='mensal'?'mensal':'pagamento único'})`).join('\n')}\n\nMensalidade: ${money(monthly)}\nValores únicos: ${money(one)}\nPrimeiro mês e valores únicos: ${money(monthly+one)}\n\nCondições\n${p.condicoes}\n\nDocumento comercial para negociação. O registro de aceite nesta ferramenta não substitui assinatura ou pagamento.`;}
function serviceRows(){return items.map((item,i)=>`<div class="service-row">${field('desc-'+i,'Serviço',item.descricao,'text','required maxlength="300"')}<label class="field">Cobrança<select id="type-${i}"><option value="mensal" ${item.tipo==='mensal'?'selected':''}>Mensal</option><option value="unico" ${item.tipo==='unico'?'selected':''}>Única</option></select></label>${field('price-'+i,'Valor (R$)',item.valor,'number','required min="0" max="100000000" step="0.01"')}${button('remove-service','Remover',`data-index="${i}"`)}</div>`).join('');}
function captureItems(){items=items.map((x,i)=>({descricao:$('desc-'+i).value,tipo:$('type-'+i).value,valor:$('price-'+i).value}));}
function renderProposal(){const p=current(),saved=data.registros.propostas.filter(x=>!p||x.cliente_id===p.id);$('panel').innerHTML=`<div class="no-print"><h2>${p?esc(name(p)):'Escolha o cliente no radar'}</h2>${p?`<p>${esc(p.cnpj)} · ${esc(p.endereco)}</p><form id="proposal-form"><h3>Serviços e valores negociados</h3><div id="services">${serviceRows()}</div>${button('add-service','Adicionar serviço')}<div class="input-grid">${field('valid-until','Válida até',validDraft,'date','required')}${area('conditions','Prazos, pagamento e condições',conditionsDraft)}</div><div class="actions"><button class="btn primary" type="submit">Salvar proposta</button>${button('preview-proposal','Revisar documento')}</div></form>`:empty('Selecione a empresa para preencher seus dados e montar a proposta.')}<section><h3>Propostas salvas</h3>${saved.slice().reverse().map(x=>`<div class="record"><strong>${esc(x.empresa)} · ${esc(x.status)}</strong><p>Validade: ${dateText(x.validade)}</p><div class="actions">${button('view-proposal','Ver documento',`data-id="${x.id}"`)}${x.status==='rascunho'?button('edit-proposal','Editar rascunho',`data-id="${x.id}"`)+button('proposal-status','Registrar apresentação',`data-id="${x.id}" data-status="apresentada"`):x.status==='apresentada'?button('proposal-status','Registrar aceite',`data-id="${x.id}" data-status="aceita"`)+button('proposal-status','Registrar recusa',`data-id="${x.id}" data-status="recusada"`):''}</div></div>`).join('')||empty('Salve uma proposta para acompanhar sua negociação.')}</section></div><section id="document-output">${proposalView?`<h2>Proposta comercial</h2><pre>${esc(proposalText(proposalView))}</pre><div class="actions">${button('print','Imprimir / PDF')}${button('download-proposal','Baixar texto')}</div>`:''}</section>`;
 if($('proposal-form'))$('proposal-form').onsubmit=e=>{e.preventDefault();run(async()=>{const body=proposalBody();await save('salvar-proposta',body,'Proposta salva');});};
}
function proposalBody(){captureItems();return {id:proposalEdit||undefined,cliente_id:selected,itens:items,validade:$('valid-until').value,condicoes:$('conditions').value};}
function renderMetrics(){const events=data.registros.eventos.filter(e=>(!metricsStart||e.data.slice(0,10)>=metricsStart)&&(!metricsEnd||e.data.slice(0,10)<=metricsEnd));const types=[['contato','Contatos realizados'],['visita','Visitas realizadas'],['proposta','Propostas apresentadas'],['venda','Aceites registrados']];const values=types.map(([k,l])=>[events.filter(e=>e.tipo===k).length,l]);numbers(values);const max=Math.max(1,...values.map(x=>x[0]));const phases={};data.leads.forEach(p=>{const f=p.fase||'novo';phases[f]=(phases[f]||0)+1;});$('app').innerHTML=`<article class="commercial-panel"><h2>Atividades registradas</h2><p>Contagens de eventos no período. Não representam etapas obrigatórias de um funil, faturamento ou pagamentos.</p><div class="input-grid no-print">${field('from','De',metricsStart,'date')}${field('until','Até',metricsEnd,'date')}</div>${values.map(([v,l])=>`<div class="metric-bar"><span>${l}</span><meter min="0" max="${max}" value="${v}" aria-label="${l}">${v}</meter><strong>${v}</strong></div>`).join('')}${!events.length?empty('Ainda não há atividades neste período. Registre uma conversa, visita ou apresentação nas ferramentas comerciais.'):''}<section><h3>CRM hoje</h3><p>Distribuição atual das ${data.leads.length} oportunidades. Este retrato não muda com o filtro de datas.</p><div class="commercial-numbers">${Object.entries(phases).map(([k,v])=>`<div><strong>${v}</strong><span>${esc(({novo:'Novos',contato:'Em contato',demo:'Demonstração',demo_agendada:'Demonstração agendada',proposta:'Proposta',fechado:'Fechado'})[k]||k)}</span></div>`).join('')}</div></section><section><h3>Histórico de atividades</h3><div class="table-wrap"><table><thead><tr><th>Data</th><th>Empresa</th><th>Atividade</th></tr></thead><tbody>${events.slice().reverse().map(e=>`<tr><td>${dateText(e.data)}</td><td>${esc(name(customer(e.cliente_id)))}</td><td>${esc(({contato:'Contato realizado',visita:'Visita realizada',proposta:'Proposta apresentada',venda:'Aceite registrado',recusa:'Recusa registrada'})[e.tipo]||e.tipo)}</td></tr>`).join('')}</tbody></table></div></section></article>`;['from','until'].forEach(id=>$(id).onchange=()=>{metricsStart=$('from').value;metricsEnd=$('until').value;if(metricsStart&&metricsEnd&&metricsStart>metricsEnd){error(new Error('A data inicial deve ser anterior à final.'));return;}$('feedback').hidden=true;renderMetrics();});}
async function run(fn){if(busy)return;busy=true;$('feedback').hidden=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){error(e);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
function download(value){const url=URL.createObjectURL(new Blob([value],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='proposta-trudata.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||busy)return;if(b.dataset.select){captureVisits();selected=b.dataset.select;proposalView=null;proposalEdit='';conditionsDraft='';validDraft=today();renderList();renderPanel();return;}const a=b.dataset.action;if(!a)return;run(async()=>{
 if(a==='apply-address'){const index=Number(b.dataset.index);if(!preview)throw new Error('Consulte o endereço novamente.');await save('aplicar-endereco',{token:preview.token,indice:index,confirmado:$('confirm-'+index).checked},'Endereço atualizado');}
 if(a==='add-stop'){captureVisits();if(stops.length>=8)throw new Error('A agenda aceita até oito empresas.');if(stops.some(s=>s.id===selected))throw new Error('Empresa já adicionada.');stops.push({id:selected,hora:String(9+stops.length).padStart(2,'0')+':00'});renderVisits();}
 if(a==='remove-stop'||a==='up-stop'){captureVisits();stops.forEach((s,i)=>s.hora=$('hour-'+i).value);const i=Number(b.dataset.index);if(a==='remove-stop')stops.splice(i,1);else [stops[i-1],stops[i]]=[stops[i],stops[i-1]];renderVisits();}
 if(a==='finish-visit')await save('concluir-visita',{plano:b.dataset.plan,id:b.dataset.id},'Visita registrada');
 if(a==='add-service'||a==='remove-service'){captureItems();if(a==='add-service'){if(items.length>=20)throw new Error('Use até vinte serviços.');items.push({descricao:'',tipo:'mensal',valor:''});}else{if(items.length===1)throw new Error('A proposta precisa de pelo menos um serviço.');items.splice(Number(b.dataset.index),1);}$('services').innerHTML=serviceRows();}
 if(a==='preview-proposal'){if(!$('proposal-form').reportValidity())return;const body=proposalBody();proposalView={...body,empresa:name(current()),cnpj:current().cnpj,endereco:current().endereco};$('document-output').innerHTML=`<h2>Proposta comercial</h2><pre>${esc(proposalText(proposalView))}</pre><div class="actions">${button('print','Imprimir / PDF')}${button('download-proposal','Baixar texto')}</div>`;}
 if(a==='edit-proposal'){const p=data.registros.propostas.find(p=>p.id===b.dataset.id);selected=p.cliente_id;proposalEdit=p.id;items=p.itens.map(i=>({...i}));conditionsDraft=p.condicoes;validDraft=p.validade;proposalView=null;renderList();renderProposal();}
 if(a==='view-proposal'){proposalView=data.registros.propostas.find(p=>p.id===b.dataset.id);renderProposal();$('document-output').scrollIntoView({block:'start'});}
 if(a==='proposal-status')await save('status-proposta',{id:b.dataset.id,status:b.dataset.status},({apresentada:'Apresentação registrada',aceita:'Aceite registrado',recusada:'Recusa registrada'})[b.dataset.status]);
 if(a==='print')window.print();if(a==='download-proposal'&&proposalView)download(proposalText(proposalView));
});});
$('refresh').onclick=()=>run(load);run(load);
})();
