"""Gera a estrutura das páginas da central revisada; não lê nem altera CRM."""
from pathlib import Path
import json, html
ROOT=Path(__file__).resolve().parents[1]
nav='''<a class="skip" href="#main">Ir para o conteúdo</a><header class="topbar"><div class="topbar-inner"><a class="brand" href="index.html"><span class="brand-mark">T</span><span class="brand-name">TruData<small>Relacionamento e crescimento</small></span></a><nav class="topnav" aria-label="Navegação principal"><a href="index.html">Aprovação</a><a href="calendario.html">Calendário</a><a href="radar_clientes.html">Radar de clientes</a><a href="ferramentas.html" aria-current="page">Ferramentas</a></nav><span class="small muted">Hansen Software · Sarandi, RS</span></div></header>'''
def page(title,body,script='',kind=''):
    return f'''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#009fe3"><title>{html.escape(title)} · TruData</title><link rel="icon" href="/painel_aprovacao/favicon.svg"><link rel="stylesheet" href="/painel_aprovacao/design-system.css"><link rel="stylesheet" href="/painel_aprovacao/ferramentas.css?v=20260921-3"></head><body class="tools-page" data-tool="{kind}">{nav}{body}{f'<script src="/painel_aprovacao/{script}?v=20260921-3" defer></script>' if script else ''}</body></html>'''

catalogue='''<main id="main"><header class="tools-heading"><div><p>Comercial, planejamento e conteúdo</p><h1>Ferramentas para o trabalho de hoje.</h1><p>Encontre o que precisa para preparar uma conversa e dar o próximo passo.</p></div><label class="field tool-search">Buscar ferramenta<input type="search" id="tool-search" placeholder="Cliente, proposta, custos…"></label></header><section class="next-step" aria-label="Atalhos para a rotina"><div><h2>Qual é o próximo passo?</h2><p>Comece pela tarefa que precisa resolver agora.</p></div><a href="radar_clientes.html"><strong>Encontrar clientes</strong><span>Explore as empresas próximas e escolha quem abordar.</span></a><a href="cadencia_sdr.html"><strong>Preparar uma conversa</strong><span>Transforme o contexto do cliente em uma mensagem clara.</span></a><a href="gerador_proposta.html"><strong>Fazer uma proposta</strong><span>Organize escopo, valores e condições em um documento.</span></a></section><div class="catalogue-layout"><aside><nav class="catalogue-nav" aria-label="Categorias de ferramentas"><button data-group="Todas" aria-pressed="true">Todas</button><button data-group="Comercial" aria-pressed="false">Comercial</button><button data-group="Planejamento" aria-pressed="false">Planejamento</button><button data-group="Conteúdo" aria-pressed="false">Conteúdo</button><p>Uma ferramenta para cada necessidade, sem atalhos repetidos.</p></nav></aside><section aria-labelledby="catalogue-title"><div class="catalogue-top"><h2 id="catalogue-title">Todas as ferramentas</h2><span class="small muted" id="tool-count" role="status"></span></div><div id="tool-list"></div><noscript>Ative o JavaScript para buscar no catálogo. Você também pode usar os atalhos acima.</noscript></section></div><footer class="catalogue-note"><details><summary>O que mudou nesta central?</summary><p>As ferramentas repetidas foram reunidas. Saíram do catálogo os painéis com métricas fictícias, ações sem integração e simulações apresentadas como auditorias, pagamentos ou homologações. Os endereços antigos explicam a mudança e indicam alternativas quando existem.</p><p>Os registros do CRM e os materiais originais foram preservados. Ferramentas de planejamento geram documentos locais; os textos devem refletir o que foi combinado com o cliente.</p></details></footer></main>'''
(ROOT/'ferramentas.html').write_text(page('Ferramentas',catalogue,'ferramentas.js'),encoding='utf8')
canonical={'checkup_loja.html':('diagnostico','Diagnóstico da loja'),'tco_roi.html':('custos','Comparar custos'),'gerador_proposta.html':('proposta','Preparar proposta'),'cadencia_sdr.html':('conversa','Preparar uma conversa'),'checklist_implantacao.html':('implantacao','Planejar implantação'),'auditor_xml.html':('xml','Ler arquivo XML'),'teleprompter.html':('prompter','Teleprompter'),'demo_pdv.html':('demo','Demonstração de caixa')}
for name,(kind,title) in canonical.items():
    body=f'''<main id="main"><header class="tools-heading"><div><a href="ferramentas.html">Todas as ferramentas</a><h1 id="work-title">{title}</h1><p id="work-desc"></p></div></header><p class="work-notice" id="work-notice"></p><div class="workspace"><form id="work-form" class="work-form"><h2>Prepare os dados</h2><div class="input-grid" id="fields"></div><p id="work-error" class="work-error" role="alert" hidden></p><div class="actions"><button class="btn primary" id="generate" type="submit">Atualizar resumo</button><button class="btn" id="save-draft" type="button">Salvar rascunho</button><button class="btn" id="load-draft" type="button">Recuperar rascunho</button></div><p class="work-help">Um rascunho por ferramenta neste navegador. Baixe o resumo para guardar uma cópia.</p></form><section class="work-output" aria-labelledby="output-title"><h2 id="output-title">Seu resumo</h2><p class="placeholder" id="result-empty">Preencha os dados e atualize o resumo para revisar o resultado.</p><pre id="result" hidden></pre><div id="output-special"></div><div class="actions"><button class="btn" id="copy-result" data-output disabled>Copiar resumo</button><button class="btn" id="download-result" data-output disabled>Baixar texto</button><button class="btn" id="print-result" data-output disabled>Imprimir / PDF</button></div></section></div><noscript>Ative o JavaScript para preencher e gerar o resumo.</noscript></main><div id="work-toast" class="toast" role="status" hidden></div>'''
    (ROOT/name).write_text(page(title,body,'oficina.js',kind),encoding='utf8')

groups=[
 ('Reunida em Preparar uma conversa','cadencia_sdr.html','Mensagens, objeções e roteiros foram reunidos em um editor. A nova versão não promete envio nem atualização automática do CRM.', 'cadencia_omnichannel copiloto_audio copiloto_vendas objecoes script_coldcall disparador_whatsapp'),
 ('Reunida em Comparar custos','tco_roi.html','A comparação passa a usar valores informados, sem economia mínima forçada, taxas de perda presumidas ou preços atribuídos a concorrentes.', 'calculadora_troca calculadora_ruptura calculadora_tef simulador_tef_multibandeira payback_hardware perdas_caixa dossie_portabilidade dossie_contador hardware'),
 ('Reunida em Preparar proposta','gerador_proposta.html','A proposta agora descreve escopo e valores preenchidos. Não representa contrato assinado, pagamento confirmado ou rastreamento de leitura.', 'proposta_online proposta_rastreavel fechamento_rapido'),
 ('Reunida em Planejar implantação','checklist_implantacao.html','O planejamento registra conferências e pendências. Não promete prazo universal nem compatibilidade de equipamentos sem teste.', 'migracao_concorrentes mercados'),
 ('Reunida no Radar de clientes','radar_clientes.html','Use a base regional, os filtros e as rotas do radar. Estimativas de carteira e posição simulada deixaram de orientar a prospecção.', 'gps_campo'),
 ('Reunida no Radar de contadores','radar_clientes.html?modo=contadores','Consulte escritórios por região sem estimar automaticamente quantos clientes cada um possui.', 'contadores'),
 ('Reunida na Demonstração de caixa','demo_pdv.html','A demonstração é didática e identificada como simulação. Não emite NFC-e nem envia comandos a equipamentos.', 'simulador_contingencia emulador_cupom_termica showroom_virtual'),
 ('Retirada: integração não implementada','crm.html','A versão anterior mostrava resultados ou confirmava ações sem a integração necessária. Use o CRM para registrar o acompanhamento real.', 'painel_telemetria_propostas pesquisa_nps_ativa termometro_churn produtividade_comissoes conector_bi_openapi'),
 ('Retirada: validação não implementada','auditor_xml.html','A versão anterior não executava a auditoria ou o download anunciado. O leitor XML apenas apresenta o conteúdo de um arquivo fornecido, sem laudo fiscal.', 'auditor_sped_efd portal_contador_xml'),
 ('Retirada: requer validação fiscal','checklist_implantacao.html','Os parâmetros desta versão não têm revisão fiscal documentada. Prepare as informações da operação e confira o enquadramento com o contador.', 'calculadora_difal_st simulador_simples reforma-tributaria simulador_tributario_2026 simulador_cesta_basica_rs'),
 ('Retirada: status não consultado','ferramentas.html','A tela anterior mostrava disponibilidade sem consultar um serviço de monitoramento. Ela não deve orientar decisões sobre disponibilidade da SEFAZ.', 'status_sefaz'),
 ('Retirada: equipamento não conectado','checklist_implantacao.html','Os pesos exibidos eram gerados no navegador. Isso não testa conexão, precisão ou homologação de uma balança.', 'homologador_balancas'),
 ('Retirada: condições sem validação','gerador_proposta.html','A versão anterior apresentava garantia, bônus ou formalização sem um fluxo validado. Registre na proposta apenas as condições combinadas com o responsável comercial.', 'contrato_digital garantia_blindada programa_indicacao'),
 ('Retirada: prova social sem comprovação','index.html','Depoimentos e conversas precisam de origem verificável e autorização de uso. A versão anterior não demonstrava esses requisitos.', 'prova_social_regional simulador_print_whatsapp'),
 ('Material preservado na biblioteca','biblioteca.html','Os textos das coleções anteriores estão na biblioteca de referência para consulta e adaptação. A versão original completa também foi preservada, sem publicação automática.', 'stories carrosseis_feed roteiros_reels spots_radio estudio_brolls campanhas_ads campanhas_trafego figurinhas gerador_reels gerador_carrosseis_916 spots_radio_trilha vitrine_comercios_rs pitch'),
]
rows=[]
for decision,target,reason,names in groups:
 for stem in names.split():
    name=stem+'.html';rows.append({'arquivo':name,'decisao':decision,'destino':target,'motivo':reason})
    body=f'''<main id="main" class="retired"><p class="small muted">Revisão das ferramentas</p><h1>{html.escape(decision)}</h1><p style="margin-top:24px">{html.escape(reason)}</p><div class="actions"><a class="btn primary" id="replacement" href="{target}">Ver alternativa</a><a class="btn" href="ferramentas.html">Todas as ferramentas</a></div></main><script>const q=location.search;if(q){{const a=document.getElementById('replacement'),u=new URL(a.href);for(const [k,v] of new URLSearchParams(q))if(['cliente','cidade','decisor'].includes(k))u.searchParams.set(k,v);a.href=u.href;}}</script>'''
    (ROOT/name).write_text(page('Ferramenta revisada',body),encoding='utf8')
original=json.loads((ROOT/'qa/ferramentas-inventario.json').read_text(encoding='utf8'))
covered=set(canonical)|{r['arquivo'] for r in rows}|{'crm.html','calendario.html','radar_clientes.html'}
assert set(original)<=covered,set(original)-covered
(ROOT/'qa/ferramentas-decisoes.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf8')
audit=['# Revisão da central de ferramentas','',f'{len(original)} destinos únicos no catálogo anterior; 14 entradas na nova central.','', '## Critério', '', 'Manter operações reais. Reunir tarefas equivalentes. Retirar confirmações simuladas, métricas sem fonte e condições comerciais ou fiscais sem validação documentada. Nenhum registro de cliente ou arquivo de negócio foi alterado.', '', '## Ferramentas reformuladas','']
audit += [f'- `{name}`: {title}.' for name,(_,title) in canonical.items()]
audit += ['', '## Decisão para cada destino anterior', '', '| Página | Decisão | Alternativa |', '|---|---|---|']
audit += [f'| {r["arquivo"]} | {r["decisao"]} | {r["destino"]} |' for r in rows]
audit += ['', 'Radar, CRM e calendário mantidos. Aprovação integrada por link.', '', '## Evidências da revisão', '', '- SPED: `executarAuditoria` mostrava 1.428 documentos aprovados, sem ler arquivo.', '- Portal XML: os botões de download apenas executavam `alert`.', '- Balanças: o peso vinha de `Math.random`, sem comunicação com dispositivo.', '- Retenção e NPS: os alertas confirmavam agendamento e ações remotas inexistentes.', '- Telemetria: os registros vinham de `DADOS_MOCK`.', '- Contrato: `gerarHashSimulado` e confirmação de pagamento simulada.', '- Calculadoras: economia limitada por `Math.max`, recuperação presumida de 90% e perda fixa de 0,4%.', '- Proposta: economia anual fixa, sem relação com valores fornecidos pelo cliente.', '', '## Recuperação de referências', '', 'Os HTMLs anteriores estão preservados em `qa/ferramentas-fontes-antes.zip`. Conteúdo criativo não foi apagado do arquivo de referência. A nova central não o apresenta como pronto para publicação.', '', '## Validação', '', 'Os resumos e rascunhos da oficina são locais. Nenhuma ferramenta nova envia mensagens, processa pagamentos ou modifica o CRM. Valores de propostas são preenchidos pelo usuário; não há preços ou garantias predefinidos.']
(ROOT/'FERRAMENTAS-REVISAO.md').write_text('\n'.join(audit),encoding='utf8')
print(f'Central + {len(canonical)} ferramentas reformuladas + {len(rows)} páginas de transição geradas.')

body="""<main id="main"><header class="tools-heading"><div><a href="ferramentas.html">Todas as ferramentas</a><h1>Biblioteca de referência</h1><p>Roteiros e ideias preservados para a próxima criação.</p></div><label class="field tool-search">Buscar nas coleções<input id="library-search" type="search" placeholder="Roteiro, loja, atendimento…"></label></header><p class="work-notice">Material anterior, ainda sujeito à revisão editorial. Confira números, promessas e condições antes de usar. As alterações feitas aqui são temporárias; baixe o texto para guardá-las.</p><div class="workspace"><section class="work-form"><h2 id="library-count">Coleções</h2><div id="library-list" class="checklist-items"></div></section><section class="work-output"><h2 id="library-title">Escolha uma coleção</h2><label class="field">Texto para consultar e adaptar<textarea id="library-text" rows="22" placeholder="Abra uma coleção ao lado."></textarea></label><div class="actions"><button class="btn" id="library-copy" disabled>Copiar texto</button><button class="btn" id="library-download" disabled>Baixar texto</button></div><p id="library-status" role="status" class="work-help"></p></section></div></main><script src="/painel_aprovacao/biblioteca-dados.js?v=20260921-3"></script>"""
(ROOT/'biblioteca.html').write_text(page('Biblioteca de referência',body,'biblioteca.js'),encoding='utf8')
